// Code generated by datactl from plugin-owned tilecast.datasource.json files. DO NOT EDIT.
// Run `npm run data-sources:generate`.

package datasources

// PluginSourceManifest is one plugin-owned Data Source manifest composed
// into the Server's content catalog. PluginID is the stable id from the
// owning plugin's tilecast.plugin.json (never the plugin directory
// basename), Dir is the module's directory relative to the repository
// root, and JSON carries the exact tilecast.datasource.json bytes for
// validation and fingerprinting. The manifest beside the module stays
// authoritative; this ledger only bridges the gap Go embedding cannot
// cross.
type PluginSourceManifest struct {
	PluginID string
	Dir      string
	JSON     string
}

var pluginSourceManifests = []PluginSourceManifest{}

// PluginSourceManifests returns every plugin-owned Data Source manifest
// in directory order.
func PluginSourceManifests() []PluginSourceManifest {
	out := make([]PluginSourceManifest, len(pluginSourceManifests))
	copy(out, pluginSourceManifests)
	return out
}
