// Code generated by widgetctl from widgets/*/tilecast.widget.json. DO NOT EDIT.
// Run `npm run widgets:generate`.

//! First-class Widget components bundled in the Player Runtime the Android
//! Player ships with (docs/widgets-v2.md §7). The renderer runs the same
//! runtime artifact, so the list is fixed at release build time.

/// Latest component presentation schema the Android host applies: 2.
/// Schema 3 (declared empty policy) needs host-side empty-skip handling
/// the Android Player has not implemented yet; manifests using it are
/// incompatible until it does.
pub const COMPONENT_PRESENTATION_SCHEMA: u32 = 2;

/// `widget.<type>` capability and component version.
pub const WIDGET_COMPONENTS: &[(&str, u32)] = &[
    ("widget.tilecast.agenda", 1),
    ("widget.tilecast.cards", 1),
    ("widget.tilecast.chart", 1),
    ("widget.tilecast.clock", 2),
    ("widget.tilecast.countdown", 1),
    ("widget.tilecast.image-notice", 1),
    ("widget.tilecast.list", 1),
    ("widget.tilecast.menu-board", 1),
    ("widget.tilecast.metrics", 1),
    ("widget.tilecast.news", 1),
    ("widget.tilecast.progress", 1),
    ("widget.tilecast.qr-code", 1),
    ("widget.tilecast.spotlight", 1),
    ("widget.tilecast.status", 1),
    ("widget.tilecast.table", 1),
    ("widget.tilecast.text", 1),
    ("widget.tilecast.ticker", 1),
    ("widget.tilecast.timeline", 1),
    ("widget.tilecast.weather", 1),
];
