// Code generated by widgetctl from widgets/*/tilecast.widget.json. DO NOT EDIT.
// Run `npm run widgets:generate`.

//! First-class Widget components bundled in the Player Runtime this daemon
//! ships with (docs/widgets-v2.md §7). The renderer runs the same runtime
//! artifact, so the list is fixed at release build time.

/// Presentation schema of kind "component" presentations.
pub const COMPONENT_PRESENTATION_SCHEMA: u32 = 2;

/// `widget.<type>` capability and component version.
pub const WIDGET_COMPONENTS: &[(&str, u32)] = &[
    ("widget.tilecast.cards", 1),
    ("widget.tilecast.clock", 1),
    ("widget.tilecast.list", 1),
    ("widget.tilecast.qr-code", 1),
    ("widget.tilecast.table", 1),
];
