// Package sandbox assembles sandboxed Widget frame documents for
// Studio previews. The document template is generated by widgetctl
// from the widget-sdk frame builder, so the served bytes stay
// identical to what the isolation spike measures. The only
// server-side logic is the bundle slot: exactly one placeholder,
// replaced with the verified bundle after escaping script closers.
package sandbox

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"regexp"
	"strings"
)

// scriptCloser matches an inline script breakout case-insensitively,
// mirroring escapeInlineScript in
// packages/widget-sdk/src/sandboxed-executor.ts.
var scriptCloser = regexp.MustCompile(`(?i)</script`)

// EscapeInlineScript neutralizes script closers in bundle bytes so an
// inlined bundle cannot break out of its script block. It is an exact
// port of the widget-sdk rule; the test vectors below mirror
// test/sandboxed-executor.test.ts.
func EscapeInlineScript(bundle string) string {
	return scriptCloser.ReplaceAllString(bundle, `<\/script`)
}

// Assemble interpolates one verified bundle into the generated frame
// template. It fails closed when the template does not hold exactly
// one bundle slot.
func Assemble(bundle string) (string, error) {
	if strings.Count(Template, BundlePlaceholder) != 1 {
		return "", errors.New("sandbox frame template must hold exactly one bundle slot")
	}
	return strings.Replace(Template, BundlePlaceholder, EscapeInlineScript(bundle), 1), nil
}

// MaxFrameBytes bounds one assembled sandbox frame document: a
// maximum-size Widget bundle plus the bootstrap template with
// headroom. The frame test pins the template far below the headroom
// so a template change cannot silently eat the bundle budget.
const MaxFrameBytes = int64(1<<20 + 1<<16)

// AssembledFrame is one deterministically assembled sandbox frame: the
// exact document bytes Players verify and cache, with the hash and
// size manifest compilation and the delivery endpoint agree on.
type AssembledFrame struct {
	Document  string
	SHA256Hex string
	Size      int64
}

// AssembleFrame assembles one verified bundle and reports the exact
// bytes, hash, and size every consumer agrees on. It fails closed on
// an oversized document: Players verify exact size before activation,
// so the Server must never name bytes it cannot serve.
func AssembleFrame(bundle string) (AssembledFrame, error) {
	document, err := Assemble(bundle)
	if err != nil {
		return AssembledFrame{}, err
	}
	if int64(len(document)) > MaxFrameBytes {
		return AssembledFrame{}, fmt.Errorf("sandbox frame exceeds %d bytes", MaxFrameBytes)
	}
	sum := sha256.Sum256([]byte(document))
	return AssembledFrame{
		Document:  document,
		SHA256Hex: hex.EncodeToString(sum[:]),
		Size:      int64(len(document)),
	}, nil
}
