// Package sandbox assembles sandboxed Widget frame documents for
// Studio previews. The document template is generated by widgetctl
// from the widget-sdk frame builder, so the served bytes stay
// identical to what the isolation spike measures. The only
// server-side logic is the bundle slot: exactly one placeholder,
// replaced with the verified bundle after escaping script closers.
package sandbox

import (
	"errors"
	"regexp"
	"strings"
)

// scriptCloser matches an inline script breakout case-insensitively,
// mirroring escapeInlineScript in
// packages/widget-sdk/src/sandboxed-executor.ts.
var scriptCloser = regexp.MustCompile(`(?i)</script`)

// EscapeInlineScript neutralizes script closers in bundle bytes so an
// inlined bundle cannot break out of its script block. It is an exact
// port of the widget-sdk rule; the test vectors below mirror
// test/sandboxed-executor.test.ts.
func EscapeInlineScript(bundle string) string {
	return scriptCloser.ReplaceAllString(bundle, `<\/script`)
}

// Assemble interpolates one verified bundle into the generated frame
// template. It fails closed when the template does not hold exactly
// one bundle slot.
func Assemble(bundle string) (string, error) {
	if strings.Count(Template, BundlePlaceholder) != 1 {
		return "", errors.New("sandbox frame template must hold exactly one bundle slot")
	}
	return strings.Replace(Template, BundlePlaceholder, EscapeInlineScript(bundle), 1), nil
}
