package org.tilecast.player

import java.io.File
import javax.imageio.ImageIO
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Guards the launcher branding contract: an adaptive icon in `mipmap`, a 320x180
 * Android TV banner, and no stale or duplicated artwork. The artwork itself is
 * generated by `npm run android:branding:generate`; `npm run android:branding:check`
 * detects drift from the source SVGs.
 */
class LauncherBrandingContractTest {
    private val main = File("src/main")
    private val res = File(main, "res")
    private val manifest = File(main, "AndroidManifest.xml").readText()

    private fun applicationAttribute(name: String): String? =
        Regex("""<application\b[^>]*?android:$name="([^"]*)"""", RegexOption.DOT_MATCHES_ALL)
            .find(manifest)
            ?.groupValues
            ?.get(1)

    private fun dimensions(file: File): Pair<Int, Int> {
        assertTrue("${file.path} is missing", file.isFile)
        val image = checkNotNull(ImageIO.read(file)) { "${file.path} is not a readable image" }
        return image.width to image.height
    }

    @Test
    fun manifestUsesAdaptiveMipmapIconAndTvBannerWithoutRoundIcon() {
        assertEquals("@mipmap/ic_launcher", applicationAttribute("icon"))
        assertEquals("@drawable/tilecast_banner", applicationAttribute("banner"))
        assertEquals(null, applicationAttribute("roundIcon"))
    }

    @Test
    fun adaptiveIconHasSeparateLayersAndAMonochromeLayer() {
        val xml = File(res, "mipmap-anydpi-v26/ic_launcher.xml").readText()
        assertTrue(xml.contains("<adaptive-icon"))
        assertTrue(xml.contains("<background android:drawable=\"@color/tilecast_signal_background\""))
        assertTrue(xml.contains("<foreground android:drawable=\"@drawable/ic_launcher_foreground\""))
        assertTrue(xml.contains("<monochrome android:drawable=\"@drawable/ic_launcher_foreground\""))
        assertFalse("the adaptive icon is the only launcher XML", File(res, "mipmap-anydpi-v26/ic_launcher_round.xml").exists())

        val foreground = File(res, "drawable/ic_launcher_foreground.xml").readText()
        assertTrue(foreground.contains("android:viewportWidth=\"108\""))
        assertEquals("one path per tile of the Tilecast mark", 3, Regex("<path\\b").findAll(foreground).count())
        assertFalse("the mask belongs to Android, not the artwork", foreground.contains("<clip-path"))
    }

    @Test
    fun legacyIconsExistAtEveryLauncherDensity() {
        val sizes = mapOf("mdpi" to 48, "hdpi" to 72, "xhdpi" to 96, "xxhdpi" to 144, "xxxhdpi" to 192)
        for ((density, size) in sizes) {
            assertEquals(size to size, dimensions(File(res, "mipmap-$density/ic_launcher.png")))
        }
    }

    @Test
    fun tvBannerIs320By180AtXhdpiAndScalesCleanly() {
        assertEquals(320 to 180, dimensions(File(res, "drawable-xhdpi/tilecast_banner.png")))
        assertEquals(480 to 270, dimensions(File(res, "drawable-xxhdpi/tilecast_banner.png")))
    }

    @Test
    fun bannerIsNotLocalizedBecauseTheWordmarkIsAProductName() {
        val localized =
            res.listFiles { f -> f.isDirectory }.orEmpty().flatMap { dir ->
                dir.listFiles { f -> f.name.startsWith("tilecast_banner") }.orEmpty().toList()
            }.filter { !Regex("drawable(-(xhdpi|xxhdpi))?").matches(it.parentFile.name) }
        assertTrue("unexpected banner variants: $localized", localized.isEmpty())
        assertFalse(
            "a default-density banner would shadow the 320x180 asset",
            File(res, "drawable/tilecast_banner.xml").exists() || File(res, "drawable/tilecast_banner.png").exists(),
        )
    }

    @Test
    fun obsoleteLauncherArtworkIsGone() {
        assertFalse(File(res, "drawable/tilecast_icon.xml").exists())
        assertNotNull(
            "launcher resources must be generated from branding/source",
            File("../branding/source/tilecast-mark.svg").takeIf { it.isFile },
        )
        assertTrue(File("../branding/source/tilecast-wordmark.svg").isFile)
        assertEquals(512 to 512, dimensions(File("../branding/play-store/tilecast-play-icon-512.png")))
    }
}
