/**
 * Generated artifacts. Only what a toolchain cannot discover by itself is
 * generated: the portable JSON Schema, and the plugin-owned Data Source
 * ledger the Server embeds. Studio and the Player read module manifests
 * from the release catalog API; the Server embeds root manifests with
 * go:embed and reads plugin-owned manifests from the generated ledger,
 * because Go embedding cannot reach outside the data-sources package tree
 * into plugins/.
 */
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import * as prettier from "prettier";
import { goQuoted } from "../../../widget-sdk/tools/widgetctl/generate.ts";
import {
  dataSourceManifestJSONSchema,
  MANIFEST_FILE,
} from "../../src/manifest.ts";
import type { Repo } from "./repo.ts";

export const JSON_SCHEMA =
  "packages/data-source-sdk/schema/tilecast-datasource.schema.json";
/** Server-side ledger of plugin-owned Data Source manifests. */
export const PLUGIN_SOURCE_LEDGER = "data-sources/plugin_sources.gen.go";

async function format(text: string, path: string, root: string) {
  const options = (await prettier.resolveConfig(join(root, path))) ?? {};
  return prettier.format(text, { ...options, filepath: join(root, path) });
}

export interface LedgerSource {
  dir: string;
  pluginId: string;
  json: string;
}

/**
 * The plugin-owned Data Source ledger: every plugin Data Source manifest
 * with its stable plugin identity and exact manifest bytes. The file is
 * gofmt-clean by construction; data-sources:check fails when the
 * committed file differs from a fresh generation.
 */
export function pluginSourceLedger(sources: LedgerSource[]): string {
  const entries = [...sources]
    .sort((a, b) => (a.dir < b.dir ? -1 : a.dir > b.dir ? 1 : 0))
    .map(
      (source) =>
        `\t{PluginID: ${goQuoted(source.pluginId)}, Dir: ${goQuoted(source.dir)}, JSON: ${goQuoted(source.json)}}`,
    )
    .join(",\n");
  const table =
    entries.length === 0
      ? "var pluginSourceManifests = []PluginSourceManifest{}"
      : `var pluginSourceManifests = []PluginSourceManifest{\n${entries},\n}`;
  return `// Code generated by datactl from plugin-owned tilecast.datasource.json files. DO NOT EDIT.
// Run \`npm run data-sources:generate\`.

package datasources

// PluginSourceManifest is one plugin-owned Data Source manifest composed
// into the Server's content catalog. PluginID is the stable id from the
// owning plugin's tilecast.plugin.json (never the plugin directory
// basename), Dir is the module's directory relative to the repository
// root, and JSON carries the exact tilecast.datasource.json bytes for
// validation and fingerprinting. The manifest beside the module stays
// authoritative; this ledger only bridges the gap Go embedding cannot
// cross.
type PluginSourceManifest struct {
\tPluginID string
\tDir      string
\tJSON     string
}

${table}

// PluginSourceManifests returns every plugin-owned Data Source manifest
// in directory order.
func PluginSourceManifests() []PluginSourceManifest {
\tout := make([]PluginSourceManifest, len(pluginSourceManifests))
\tcopy(out, pluginSourceManifests)
\treturn out
}
`;
}

/**
 * Compare generated content with the files on disk. Paths whose content
 * differs (or files that are missing) are stale.
 */
export function stale(repo: Repo, generated: Map<string, string>): string[] {
  const stalePaths: string[] = [];
  for (const [path, content] of generated) {
    const full = join(repo.root, path);
    if (!existsSync(full) || readFileSync(full, "utf8") !== content) {
      stalePaths.push(path);
    }
  }
  return stalePaths;
}

export async function generate(repo: Repo): Promise<Map<string, string>> {
  const files = new Map<string, string>();
  files.set(
    JSON_SCHEMA,
    await format(
      JSON.stringify(dataSourceManifestJSONSchema()),
      JSON_SCHEMA,
      repo.root,
    ),
  );
  const ledger: LedgerSource[] = [];
  for (const source of repo.sources) {
    if (source.source.kind !== "plugin") continue;
    ledger.push({
      dir: source.dir,
      pluginId: source.source.pluginId,
      json: readFileSync(join(source.path, MANIFEST_FILE), "utf8"),
    });
  }
  files.set(PLUGIN_SOURCE_LEDGER, pluginSourceLedger(ledger));
  return files;
}
