// Generated by apps/ios/scripts/generate-navigation-icons.mjs from Lucide
// 1.48.0. Do not edit; run `npm run ios:icons:generate`.

/// Lucide icons for the app's own controls in native navigation.
enum AppIcon {
    static let more = "Lucide/ellipsis"
    static let server = "Lucide/server"
    static let add = "Lucide/plus"
    static let manage = "Lucide/settings"
    static let reload = "Lucide/rotate-cw"
    static let current = "Lucide/check"
}
