// Code generated by widgetctl from widgets/*/tilecast.widget.json. DO NOT EDIT.
// Run `npm run widgets:generate`.

/**
 * The first-class Widget components this runtime bundles, as Players report
 * them in nativePresentationCapabilities (docs/widgets-v2.md §7). Hosts that
 * are not built with Vite (the Electron main process) import this list; the
 * runtime's tests prove it equals what discovery finds.
 */
export const WIDGET_COMPONENT_CAPABILITIES: Readonly<Record<string, number>> =
  Object.freeze({
    "widget.tilecast.agenda": 1,
    "widget.tilecast.cards": 1,
    "widget.tilecast.clock": 2,
    "widget.tilecast.countdown": 1,
    "widget.tilecast.image-notice": 1,
    "widget.tilecast.list": 1,
    "widget.tilecast.menu-board": 1,
    "widget.tilecast.metrics": 1,
    "widget.tilecast.news": 1,
    "widget.tilecast.progress": 1,
    "widget.tilecast.qr-code": 1,
    "widget.tilecast.table": 1,
    "widget.tilecast.text": 1,
    "widget.tilecast.ticker": 1,
    "widget.tilecast.weather": 1,
  });

/** Presentation schema of kind "component" presentations. */
export const COMPONENT_PRESENTATION_SCHEMA_VERSION = 2;
