package org.tilecast.player.network

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable data class DataEnvelope<T>(val data: T)
@Serializable data class ErrorEnvelope(val error: ApiErrorBody? = null)
@Serializable data class ApiErrorBody(val code: String = "unknown_error", val message: String = "Tilecast could not complete the request")
@Serializable data class ServerIdentity(val product: String, val installationId: String, val organizationName: String, val apiVersion: String, val pairingEnabled: Boolean)
@Serializable data class DeviceMetadata(val playerInstallationId: String, val platform: String, val manufacturer: String, val model: String, val androidVersion: String, val playerVersion: String, val screenWidth: Int, val screenHeight: Int, val density: Float, val locale: String, val timezone: String)
@Serializable data class PairingCreateRequest(val installationId: String, val metadata: DeviceMetadata)
@Serializable data class PairingSession(val id: String, val code: String, val pollSecret: String, val expiresAt: String, val serverTime: String, val pollingIntervalSeconds: Int, val approvalUrl: String, val organizationName: String)
@Serializable data class PairingPoll(val status: String, val expiresAt: String, val screenId: String? = null, val enrollmentToken: String? = null, val failureReason: String? = null)
@Serializable data class EnrollmentRequest(val pairingSessionId: String, val enrollmentToken: String)
@Serializable data class EnrollmentResult(val screenId: String, val screenName: String, val deviceCredential: String)
@Serializable data class PreviewSession(val active: Boolean = false, val expiresAt: String? = null, val captureIntervalSeconds: Int = 20, val captureNow: Boolean = false)
@Serializable data class LiveStreamSession(
    val id: String? = null,
    val active: Boolean = false,
    val expiresAt: String? = null,
    val frameIntervalMillis: Int = 125,
    val maxWidth: Int = 640,
    val maxHeight: Int = 360,
    val maxFrameBytes: Int = 100 * 1024,
)
object PlayerPresentationSupport {
    val schemas = listOf(1)
    val native = mapOf(
        "layout.surface" to 1, "layout.box" to 1, "layout.row" to 1, "layout.column" to 1, "layout.stack" to 1, "layout.grid" to 1, "layout.spacer" to 1, "layout.divider" to 1,
        "content.text" to 1, "content.icon" to 2, "content.asset_image" to 2, "content.badge" to 1, "content.progress" to 2, "content.qr_code" to 1, "content.marquee" to 1, "content.line_chart" to 2, "content.bar_chart" to 2, "content.donut_chart" to 2,
        "collection.repeat" to 2, "collection.conditional" to 2, "collection.grouped_sections" to 1, "binding.core" to 2, "format.typed" to 2, "selection.relative_date" to 1, "selection.temporal" to 1, "playback.auto_skip" to 1,
    )
    const val webRuntimeVersion = 2
    const val webBundleLimitBytes = 20L * 1024 * 1024
}
@Serializable data class HeartbeatRequest(val screenWidth: Int, val screenHeight: Int, val availableStorageBytes: Long? = null, val uptimeSeconds: Long? = null, val playerVersion: String,val playerVersionCode:Long?=null,val presentationSchemaVersions:List<Int> = PlayerPresentationSupport.schemas,val nativePresentationCapabilities:Map<String,Int> = PlayerPresentationSupport.native,val webRuntimeVersion:Int=PlayerPresentationSupport.webRuntimeVersion,val webBundleLimitBytes:Long=PlayerPresentationSupport.webBundleLimitBytes,val androidSdk:Int?=null,val installerSource:String?=null,val installPermissionStatus:String?=null,
    val activeManifestVersion: Long? = null, val pendingManifestVersion: Long? = null, val assignedPlaylistId: String? = null,
    val currentItemId: String? = null, val currentAssetId: String? = null, val playbackState: String? = null,
    val downloadQueueCount: Int? = null, val downloadedBytes: Long? = null, val requiredBytes: Long? = null,
    val cacheUsedBytes: Long? = null, val cacheLimitBytes: Long? = null, val lastSynchronizationError: String? = null, val lastPlaybackError: String? = null,
    val currentScheduleId:String?=null,val currentPlaylistId:String?=null,val selectionSource:String?=null,val nextTransitionAt:String?=null,val deviceClockOffsetSeconds:Long?=null,val scheduleEvaluationError:String?=null,val scheduleManifestVersion:Long?=null,
    val currentWebsiteAssetId:String?=null,val websiteState:String?=null,val websiteLoadStartedAt:String?=null,val websiteLoadCompletedAt:String?=null,val websiteFailureCategory:String?=null,val websiteBlockedNavigationCount:Int?=null,val websiteCurrentHost:String?=null,val websiteFallbackShown:Boolean?=null,val websiteRendererRecoveryCount:Int?=null,
    val currentWidgetId:String?=null,val widgetProvider:String?=null,val widgetState:String?=null,val widgetError:String?=null,
    val activeTakeoverId:String?=null,val takeoverState:String?=null,val takeoverPreparationProgress:Int?=null,val playbackDisabled:Boolean?=null,val lastCommandId:String?=null,val lastCommandState:String?=null,val lastCommandResult:String?=null,val lastCommandCompletedAt:String?=null,val activeConfigRevision:Long?=null,val configurationError:String?=null,
    val currentUpdateDeploymentId:String?=null,val updateState:String?=null,val updateDownloadedBytes:Long?=null,val updateExpectedBytes:Long?=null,val updateError:String?=null,
    val configuredReliabilityMode:String?=null,val effectiveReliabilityMode:String?=null,val foregroundState:String?=null,val lastForegroundExitAt:String?=null,val lastForegroundPackage:String?=null,
    val bootRecoveryResult:String?=null,val lastSuccessfulColdBootAt:String?=null,val immersiveModeActive:Boolean?=null,val keepScreenOn:Boolean?=null,
    val managedKioskCapability:String?=null,val deviceOwnerState:String?=null,val lockTaskState:String?=null,val accessibilityServiceState:String?=null,val accessibilityReturnState:String?=null,val accessibilityReturnAttempts:Int?=null,
    val activeHoursState:String?=null,val sleepCapability:String?=null,val lastSleepRequestResult:String?=null,val lastWakeResult:String?=null,val recoveryLevel:Int?=null,val recoveryCount:Int?=null,val safeMode:Boolean?=null,val lastWatchdogFailure:String?=null,val lastWatchdogRecoveryAt:String?=null,val maintenanceSessionExpiresAt:String?=null,val adminPinChangedAt:String?=null,
    val commissioningState:String?=null,val commissioningStep:String?=null,val commissioningCompletedAt:String?=null,val cachedFallbackAvailable:Boolean?=null,val lastHealthyPlaybackAt:String?=null,val lastPlaylistTransitionAt:String?=null,val lastSuccessfulSyncAt:String?=null,val lastServerConnectionAt:String?=null,val bootAttemptCount:Int?=null,val bootLastAttemptAt:String?=null,val bootLaunchVerified:Boolean?=null,val updateReadiness:String?=null,val selfTestResult:String?=null,val selfTestCompletedAt:String?=null)

@Serializable data class ManifestBranding(val logoAssetId:String?=null,val logoVariantId:String?=null)
@Serializable data class PlayerManifest(val schemaVersion: Int, val manifestVersion: Long, val screenId: String, val generatedAt: String, val mode: String, val playlist: ManifestPlaylist? = null, val directFallbackPlaylist:ManifestPlaylist?=null,val playlists:List<ManifestPlaylist> = emptyList(),val layout:ManifestLayout?=null,val directFallbackLayout:ManifestLayout?=null,val layouts:List<ManifestLayout> = emptyList(),val schedules:List<ManifestSchedule> = emptyList(),val assets: List<ManifestAsset> = emptyList(),val branding:ManifestBranding?=null,val websites:List<ManifestWebsite> = emptyList(),val widgets:List<ManifestWidget> = emptyList(),val dataSources:List<ManifestDataSource> = emptyList(),val presentationOverride:ManifestPresentationOverride?=null,val takeover:ManifestTakeover?=null,val emergency:ManifestTakeover?=null,val plugins:List<ManifestPlugin> = emptyList(),val syncGroup:ManifestSyncGroup?=null,val canvas:ManifestCanvas?=null,val viewport:ManifestViewport?=null,val serverTime:String?=null,val prefetchHorizonDays:Int=14,val activationGraceSeconds:Int=30) {
    val effectiveTakeover: ManifestTakeover? get() = takeover ?: emergency
}
@Serializable data class ManifestPlugin(val id:String,val type:String,val version:Int,val config:ManifestPluginConfig)
/**
 * The plugin channel carries one array for every built-in plugin, so one config
 * shape covers all of them and every field a given plugin does not use keeps its
 * default. `type` and `version` say which fields are meaningful; a resolver that
 * reads a field belonging to another plugin is the bug this makes visible rather
 * than one polymorphic serializer per bar would.
 */
@Serializable data class ManifestPluginConfig(val name:String="",val message:String="",val scheduleType:String="",val targetTime:String?=null,val daysOfWeek:List<Int> = emptyList(),val oneTimeAt:String?=null,val timezone:String="UTC",val leadTimeSeconds:Int=0,val completionText:String="",val showConfetti:Boolean=false,val displayMode:String="overlay",val heightPx:Int=72,val progressFill:String="none",val contentPadding:Int=4,val textScale:Int=100,val urgencyEnabled:Boolean=false,val startingSoonSeconds:Int=300,val urgentSeconds:Int=60,val pulseSeconds:Int=10,val priority:Int=0,val severity:String="",val event:String="",val speed:String="medium",val expiresAt:String="")
@Serializable data class ManifestSyncGroup(val id:String,val playbackEpoch:String)
@Serializable data class ManifestCanvas(val width:Int,val height:Int)
@Serializable data class ManifestViewport(val x:Int,val y:Int,val width:Int,val height:Int,val rotation:Int=0,val order:Int=0,val bezelLeft:Int=0,val bezelTop:Int=0,val bezelRight:Int=0,val bezelBottom:Int=0)
@Serializable data class ManifestTakeover(val id:String,val playlistId:String,val activatedAt:String,val expiresAt:String)
@Serializable data class ManifestPresentationOverride(val id:String,val contentType:String,val contentId:String,val contentName:String,val startedAt:String,val expiresAt:String?=null,val playlistId:String?=null,val layoutId:String?=null,val wakeDisplay:Boolean=false)
@Serializable data class ManifestPlaylist(val id: String, val revision: Long, val name: String, val items: List<ManifestItem>)
@Serializable data class ManifestLayout(val id:String,val revisionId:String,val revision:Long,val documentSha256:String,val document:LayoutDocument)
@Serializable data class ManifestDisplayControlAction(val type:String,val input:String?=null,val volume:Int?=null,val brightness:Int?=null)
@Serializable data class ManifestSchedule(val id:String,val playlistId:String?=null,val type:String,val timezone:String,val priority:Int,val specificity:Int,val layoutId:String?=null,val displayAction:ManifestDisplayControlAction?=null,val startDate:String?=null,val endDate:String?=null,val oneTimeStart:String?=null,val oneTimeEnd:String?=null,val dailyStart:String?=null,val dailyEnd:String?=null,val daysOfWeek:List<Int> = emptyList())
@Serializable data class ManifestItem(val id: String, val assetId: String, val variantId: String?=null,val assetType:String="", val durationMs: Long? = null, val fitMode: String, val transition: String, val audioEnabled: Boolean, val volume: Float, val videoStartOffsetMs: Long? = null, val videoEndOffsetMs: Long? = null, val deliveryPolicy: String,val layoutId:String?=null,val availableFrom:String?=null,val expiresAt:String?=null,val usePlayerDefaults:Boolean=false)
@Serializable data class ManifestWebsite(val assetId:String,val name:String,val url:String,val allowedHosts:List<String>,val javascriptEnabled:Boolean,val domStorageEnabled:Boolean,val cookiePolicy:String,val reloadPolicy:String,val refreshIntervalSeconds:Int?=null,val loadTimeoutSeconds:Int,val zoomPercent:Int,val scrollX:Int,val scrollY:Int,val customUserAgent:String="",val backgroundColor:String="#0E141B",val failureBehavior:String,val fallbackImageAssetId:String?=null,val fallbackVariantId:String?=null)
@Serializable data class ManifestWidget(val assetId:String,val name:String,val provider:String="",val configVersion:Int=0,val configuration:kotlinx.serialization.json.JsonObject=kotlinx.serialization.json.buildJsonObject{},val presentation:WidgetPresentation?=null)
@Serializable data class ManifestDataSource(val id:String,val name:String,val provider:String="",val configVersion:Int=0,val configuration:kotlinx.serialization.json.JsonObject=kotlinx.serialization.json.buildJsonObject{},val dataDocument:DataDocument?=null)
@Serializable data class DataDocument(val schemaVersion:Int,val datasets:List<DocumentDataset> = emptyList())
@Serializable data class DocumentDataset(val id:String,val kind:String,val fields:List<DocumentField> = emptyList(),val scalar:DocumentValue?=null,val records:List<DocumentRecord> = emptyList(),val points:List<DocumentPoint> = emptyList(),val value:DocumentValue?=null,val cache:DocumentCacheState=DocumentCacheState(),val attribution:String="",val timezone:String="",val dateSelection:DocumentDateSelection?=null,val units:Map<String,String> = emptyMap())
@Serializable data class DocumentField(val key:String,val label:String,val type:String,val unit:String="",val currency:String="")
@Serializable data class DocumentRecord(val id:String,val values:Map<String,DocumentValue> = emptyMap())
@Serializable data class DocumentPoint(val at:String,val value:DocumentValue?=null,val values:Map<String,DocumentValue> = emptyMap())
@Serializable data class DocumentValue(val kind:String,val text:String?=null,val number:Double?=null,val integer:Long?=null,val boolean:Boolean?=null,val date:String?=null,val datetime:String?=null,val durationSeconds:Long?=null,val url:String?=null,val assetId:String?=null,val list:List<DocumentValue> = emptyList(),@SerialName("object") val objectValue:Map<String,DocumentValue> = emptyMap())
@Serializable data class DocumentCacheState(val cachedAt:String?=null,val staleAt:String?=null,val usingCachedData:Boolean=false,val unavailable:Boolean=false,val lastModified:String="",val upstreamExpiry:String?=null)
@Serializable data class DocumentDateSelection(val field:String,val timezone:String,val mode:String,val customStartDate:String="",val customEndDate:String="",val excludePast:Boolean=false,val noMatchBehavior:String="",val fallbackText:String="")
@Serializable data class WidgetPresentation(val schemaVersion:Int,val kind:String,val requiredCapabilities:Map<String,Int> = emptyMap(),val native:NativePresentation?=null,val web:WebSandboxPresentation?=null)
@Serializable data class NativePresentation(val root:PresentationNode)
@Serializable data class PresentationNode(val id:String="",val type:String,val props:kotlinx.serialization.json.JsonObject=kotlinx.serialization.json.buildJsonObject{},val binding:PresentationBinding?=null,val repeat:PresentationRepeat?=null,val condition:PresentationCondition?=null,val children:List<PresentationNode> = emptyList())
@Serializable data class PresentationBinding(val source:String,val dataset:String="",val path:String="",val selector:String="all",val startField:String="",val endField:String="",val value:String="",val fields:List<String> = emptyList(),val format:String="",val precision:Int?=null,val prefix:String="",val suffix:String="",val fallback:String="",val separator:String="")
@Serializable data class PresentationRepeat(val dataset:String,val limit:Int,val offset:Int=0,val selector:String="all",val startField:String="",val endField:String="")
@Serializable data class PresentationCondition(val binding:PresentationBinding,val op:String,val value:String="")
@Serializable data class WebReload(val mode:String,val intervalSeconds:Int)
@Serializable data class WebSandboxPresentation(val mode:String,val url:String="",val bundleId:String="",val entryPoint:String="",val integritySha256:String="",val packageSize:Long=0,val downloadPath:String="",val allowedHosts:List<String> = emptyList(),val externalNetworkAccess:Boolean=false,val onlineOnly:Boolean=false,val fallbackBehavior:String="placeholder",val loadTimeoutSeconds:Int=20,val lifecycle:String="destroy_on_hide",val warmSeconds:Int=0,val reload:WebReload?=null)
@Serializable data class WebsiteSourceConfig(val url:String,val displayUrl:String="",val allowedHosts:List<String>,val javascriptEnabled:Boolean=true,val domStorageEnabled:Boolean=true,val cookiePolicy:String="first_party",val reloadPolicy:String="on_each_activation",val refreshIntervalSeconds:Int?=null,val loadTimeoutSeconds:Int=20,val zoomPercent:Int=100,val scrollX:Int=0,val scrollY:Int=0,val customUserAgent:String="",val backgroundColor:String="#0E141B",val failureBehavior:String="placeholder",val fallbackImageAssetId:String?=null,val fallbackVariantId:String?=null)
@Serializable data class YouTubeSourceConfig(val url:String,val kind:String="video",val videoId:String?=null,val playlistId:String?=null,val startSeconds:Int=0,val endSeconds:Int?=null,val loop:Boolean=false,val muted:Boolean=false,val volume:Int=100,val captions:Boolean=false,val captionLanguage:String="",val controls:Boolean=false,val failureBehavior:String="placeholder",val fallbackImageAssetId:String?=null,val fallbackVariantId:String?=null,val playlistPlaybackMode:String="until_end",val fixedDurationSeconds:Int?=null)
@Serializable data class CalendarSourceConfig(val displayMode:String="upcoming",val maxEvents:Int=10,val fields:CalendarFields=CalendarFields(),val timezone:String="UTC",val emptyState:String="No events scheduled",val data:CalendarPreparedData=CalendarPreparedData())
@Serializable data class CalendarFields(val title:Boolean=true,val startTime:Boolean=true,val endTime:Boolean=false,val date:Boolean=true,val location:Boolean=true,val descriptionExcerpt:Boolean=false)
@Serializable data class CalendarPreparedData(val events:List<CalendarEvent> = emptyList(),val cachedAt:String?=null,val staleAt:String?=null,val usingCachedData:Boolean=false,val unavailable:Boolean=false)
@Serializable data class CalendarEvent(val id:String,val calendar:String,val title:String,val start:String,val end:String,val allDay:Boolean,val location:String="",val descriptionExcerpt:String="")
@Serializable data class StructuredSourceConfig(val presentation:String="list",val fields:StructuredFields=StructuredFields(),val emptyState:String="No items available",val dateSelection:DateSelection=DateSelection(),val data:StructuredPreparedData=StructuredPreparedData())
@Serializable data class DateSelection(val enabled:Boolean=false,val dateFormat:String="auto",val timezone:String="UTC",val mode:String="today",val customStartDate:String="",val customEndDate:String="",val excludePast:Boolean=false,val noMatchBehavior:String="empty",val fallbackText:String="")
@Serializable data class StructuredFields(val title:Boolean=true,val subtitle:Boolean=true,val date:Boolean=true,val author:Boolean=true,val description:Boolean=true,val image:Boolean=false,val link:Boolean=false)
@Serializable data class StructuredPreparedData(val records:List<StructuredRecord> = emptyList(),val cachedAt:String?=null,val staleAt:String?=null,val usingCachedData:Boolean=false,val unavailable:Boolean=false,val fieldCurrencies:Map<String,String> = emptyMap())
@Serializable data class StructuredRecord(val id:String,val title:String,val subtitle:String="",val date:String="",val author:String="",val description:String="",val imageUrl:String="",val link:String="",val values:Map<String,String> = emptyMap())
@Serializable data class DataSourceField(val key:String,val label:String,val type:String,val currency:String="")
@Serializable data class TypedRecord(val id:String,val values:Map<String,String> = emptyMap())
@Serializable data class TypedRecordData(val fields:List<DataSourceField> = emptyList(),val records:List<TypedRecord> = emptyList(),val cachedAt:String?=null,val staleAt:String?=null,val usingCachedData:Boolean=false,val unavailable:Boolean=false,val dateSelection:DateSelection?=null,val dateField:String="",val attribution:String="")
@Serializable data class ClockWidgetConfig(val timezone:String="",val format:String="locale",val showSeconds:Boolean=false,val foregroundColor:String="#F5F7FA",val backgroundColor:String="#0E141B",val textScale:Int?=null,val contentPadding:Int?=null)
@Serializable data class DateWidgetConfig(val timezone:String="",val format:String="locale",val foregroundColor:String="#F5F7FA",val backgroundColor:String="#0E141B",val textScale:Int?=null,val contentPadding:Int?=null)
@Serializable data class QRCodeWidgetConfig(val value:String,val label:String="",val errorCorrection:String="medium",val foregroundColor:String="#000000",val backgroundColor:String="#FFFFFF",val textScale:Int?=null,val contentPadding:Int?=null)
@Serializable data class CountdownWidgetConfig(val target:String,val timezone:String="UTC",val mode:String="countdown",val recurrence:String="none",val layout:String="stacked",val label:String="",val completionText:String="",val completionAction:String="completed_text",val showDays:Boolean=true,val showHours:Boolean=true,val showMinutes:Boolean=true,val showSeconds:Boolean=false,val foregroundColor:String="#F5F7FA",val backgroundColor:String="#0E141B",val textScale:Int?=null,val contentPadding:Int?=null)
@Serializable data class TickerWidgetConfig(val dataSourceId:String,val field:String="title",val fields:List<String> = emptyList(),val separator:String=" • ",val fieldSeparator:String=" — ",val speed:String="normal",val direction:String="left",val emptyState:String="No items available",val foregroundColor:String="#F5F7FA",val backgroundColor:String="#0E141B",val textScale:Int?=null,val contentPadding:Int?=null)
@Serializable data class FieldFormat(val field:String,val label:String="",val format:String="text",val precision:Int=0,val prefix:String="",val suffix:String="",val alignment:String="left",val width:Int=0)
@Serializable data class DisplayWidgetConfig(val dataSourceId:String,val fields:List<String> = listOf("title"),val maximumItems:Int=20,val foregroundColor:String="#F5F7FA",val backgroundColor:String="#0E141B",val textScale:Int?=null,val contentPadding:Int?=null,val emptyState:String="No items available",val primaryField:String="",val secondaryField:String="",val leadingField:String="",val trailingField:String="",val showDividers:Boolean=false,val rowSpacing:String="comfortable",val mode:String="records",val labelField:String="",val valueField:String="",val columns:List<FieldFormat> = emptyList(),val showHeader:Boolean=false,val alternatingRows:Boolean=false,val dateField:String="",val timeField:String="",val titleField:String="",val locationField:String="",val descriptionField:String="",val groupByDay:Boolean=false)
@Serializable data class MetricWidgetConfig(val dataSourceId:String,val valueField:String,val label:String="",val labelField:String="",val secondaryField:String="",val format:String="number",val precision:Int=0,val prefix:String="",val suffix:String="",val alignment:String="center",val emptyState:String="No value available",val foregroundColor:String="#F5F7FA",val backgroundColor:String="#0E141B",val textScale:Int?=null,val contentPadding:Int?=null)
@Serializable data class CardsWidgetConfig(val dataSourceId:String,val titleField:String,val subtitleField:String="",val bodyField:String="",val badgeField:String="",val columns:Int=2,val maximumItems:Int=6,val density:String="comfortable",val emptyState:String="No items available",val foregroundColor:String="#F5F7FA",val backgroundColor:String="#0E141B",val textScale:Int?=null,val contentPadding:Int?=null)
@Serializable data class WeatherWidgetConfig(val dataSourceId:String,val showLocation:Boolean=true,val showCurrent:Boolean=true,val showHumidity:Boolean=true,val showWind:Boolean=true,val showPrecipitation:Boolean=true,val forecastDays:Int=5,val foregroundColor:String="#F5F7FA",val backgroundColor:String="#0E141B",val textScale:Int?=null,val contentPadding:Int?=null)
@Serializable data class ManifestAsset(val assetId: String, val variantId: String, val mimeType: String, val sha256: String, val fileSize: Long, val width: Int? = null, val height: Int? = null, val durationSeconds: Double? = null, val downloadPath: String, val availableFrom: String? = null, val expiresAt: String? = null)
data class ManifestResponse(val manifest: PlayerManifest?, val rawJson: String?, val etag: String?, val notModified: Boolean)
@Serializable data class PlayerConfig(val schemaVersion:Int,val configRevision:Long,val generatedAt:String,val branding:PlayerBranding=PlayerBranding(),val playback:PlayerPlaybackDefaults=PlayerPlaybackDefaults(),val cache:PlayerCachePolicy=PlayerCachePolicy(),val sync:PlayerSyncPolicy=PlayerSyncPolicy(),val website:PlayerWebsitePolicy=PlayerWebsitePolicy(),val reliability:PlayerReliabilityPolicy=PlayerReliabilityPolicy(),val power:PlayerPowerPolicy=PlayerPowerPolicy(),val managedKiosk:ManagedKioskPolicy=ManagedKioskPolicy(),val accessibility:AccessibilityControlPolicy=AccessibilityControlPolicy(),val updates:PlayerUpdatePolicy=PlayerUpdatePolicy())
@Serializable data class PlayerBranding(val organizationName:String="Tilecast",val logoAssetId:String?=null,val backgroundColor:String="#0E141B",val textColor:String="#F5F7FA",val noContentTitle:String="No content assigned",val noContentMessage:String="This screen is ready for content.",val disabledTitle:String="Playback disabled",val disabledMessage:String="This screen remains connected to Tilecast Studio.",val footerText:String="")
@Serializable data class RegionalFormatting(val locale:String,val timezone:String,val dateFormat:String,val timeFormat:String,val firstDayOfWeek:String)
@Serializable data class PlayerPlaybackDefaults(val defaultVolume:Double=.5,val defaultFitMode:String="contain",val defaultImageDurationSeconds:Int=10,val defaultTransition:String="none",val defaultAudioEnabled:Boolean=true,val resumeAfterRestart:Boolean=true,val identifyShowsLocation:Boolean=true,val screenLocation:String="",val regionalFormat:RegionalFormatting?=null)
@Serializable data class PlayerCachePolicy(val maximumBytes:Long=8589934592,val minimumFreeBytes:Long=1073741824,val concurrentDownloads:Int=2,val automaticThresholdBytes:Long=268435456)
@Serializable data class PlayerSyncPolicy(val manifestReconciliationSeconds:Int=300,val statusReportSeconds:Int=60)
@Serializable data class PlayerWebsitePolicy(val timeoutSeconds:Int=20,val cookiePolicy:String="first_party",val clearOnRestart:Boolean=false,val defaultJavascript:Boolean=true,val defaultDomStorage:Boolean=true,val defaultTimeoutSeconds:Int=20,val defaultCookiePolicy:String="first_party",val defaultReloadPolicy:String="on_each_activation",val minimumRefreshSeconds:Int=30,val defaultFailureBehavior:String="placeholder",val defaultZoomPercent:Int=100,val defaultFallbackImageId:String="")
@Serializable data class PlayerReliabilityPolicy(val mode:String="standard",val launchAfterBoot:Boolean=true,val immersiveMode:Boolean=true,val foregroundWatchdogEnabled:Boolean=true,val playbackStallSeconds:Int=30,val webviewStallSeconds:Int=45,val maximumProcessRestarts:Int=3,val restartWindowMinutes:Int=10,val safeModeEnabled:Boolean=true)
@Serializable data class PlayerPowerPolicy(val activeHoursEnabled:Boolean=false,val activeHoursTimezone:String="UTC",val activeHoursDays:List<Int> = listOf(1,2,3,4,5),val activeHoursStart:String="06:30",val activeHoursEnd:String="16:00",val startupGraceSeconds:Int=30,val shutdownPrepareSeconds:Int=60,val keepScreenOn:Boolean=true,val sleepOutsideActiveHours:Boolean=false,val outsideActiveHoursDisplay:String="black",val outsideActiveHoursText:String="",val blackScreenFallback:Boolean=true)
@Serializable data class ManagedKioskPolicy(val lockTaskEnabled:Boolean=false,val blockOverlays:Boolean=true,val allowSettingsDuringAdmin:Boolean=true,val adminSessionMinutes:Int=15)
@Serializable data class AccessibilityControlPolicy(val controlAssistEnabled:Boolean=true,val returnDelaySeconds:Int=10,val allowedPackages:List<String> = emptyList(),val pauseDuringUpdates:Boolean=true,val pauseDuringAdminSession:Boolean=true,val reportForegroundPackage:Boolean=false,val maximumReturns:Int=3,val returnWindowMinutes:Int=10)
@Serializable data class PlayerUpdatePolicy(val channel:String="stable")
data class PlayerConfigResponse(val config:PlayerConfig?,val rawJson:String?,val etag:String?,val notModified:Boolean)
@Serializable data class PlayerCommand(val id:String,val type:String,val payload:kotlinx.serialization.json.JsonObject = kotlinx.serialization.json.buildJsonObject{},val idempotencyKey:String,val state:String,val createdAt:String,val expiresAt:String)
@Serializable data class PlayerCommandList(val items:List<PlayerCommand> = emptyList())
@Serializable data class PlayerUpdateMetadata(val releaseId:String,val applicationId:String,val versionCode:Long,val versionName:String,val minimumSdk:Int,val apkSizeBytes:Long,val apkSha256:String,val signingCertificateSha256:String,val apkPath:String,val artifactId:String="")

@Serializable data class PlayerRuntimeStatus(
    val activeManifestVersion: Long? = null, val pendingManifestVersion: Long? = null, val assignedPlaylistId: String? = null,
    val currentItemId: String? = null, val currentAssetId: String? = null, val playbackState: String? = null,
    val downloadQueueCount: Int? = null, val downloadedBytes: Long? = null, val requiredBytes: Long? = null,
    val cacheUsedBytes: Long? = null, val cacheLimitBytes: Long? = null, val lastSynchronizationError: String? = null,
    val lastPlaybackError: String? = null,val currentScheduleId:String?=null,val currentPlaylistId:String?=null,val selectionSource:String?=null,val nextTransitionAt:String?=null,val deviceClockOffsetSeconds:Long?=null,val scheduleEvaluationError:String?=null,val scheduleManifestVersion:Long?=null,
    val currentWebsiteAssetId:String?=null,val websiteState:String?=null,val websiteLoadStartedAt:String?=null,val websiteLoadCompletedAt:String?=null,val websiteFailureCategory:String?=null,val websiteBlockedNavigationCount:Int?=null,val websiteCurrentHost:String?=null,val websiteFallbackShown:Boolean?=null,val websiteRendererRecoveryCount:Int?=null,
    val currentWidgetId:String?=null,val widgetProvider:String?=null,val widgetState:String?=null,val widgetError:String?=null,
)

class ApiException(val status: Int, val code: String, override val message: String) : Exception(message)
