package org.tilecast.player.network

// Code generated by scripts/generate-player-contracts.mjs; DO NOT EDIT.
// Source: packages/manifest-schema/presentation-capabilities.json
object PresentationCapabilities {
    /** Declarative presentation capabilities implemented by the shared Player Runtime. */
    val SHARED_RUNTIME_DECLARATIVE_PRESENTATION_CAPABILITIES: Map<String, Int> = linkedMapOf(
        "binding.core" to 2,
        "collection.conditional" to 2,
        "collection.grouped_sections" to 1,
        "collection.repeat" to 2,
        "content.asset_image" to 2,
        "content.badge" to 1,
        "content.bar_chart" to 2,
        "content.donut_chart" to 2,
        "content.icon" to 2,
        "content.line_chart" to 2,
        "content.marquee" to 1,
        "content.progress" to 2,
        "content.qr_code" to 1,
        "content.text" to 1,
        "environment.time" to 1,
        "format.typed" to 2,
        "layout.box" to 1,
        "layout.column" to 1,
        "layout.divider" to 1,
        "layout.grid" to 1,
        "layout.row" to 1,
        "layout.spacer" to 1,
        "layout.stack" to 1,
        "layout.surface" to 1,
        "playback.auto_skip" to 1,
        "selection.relative_date" to 1,
        "selection.temporal" to 1,
    )

    /** Compatibility floor implemented by every currently supported legacy Player. */
    val BASELINE_DECLARATIVE_PRESENTATION_CAPABILITIES: Map<String, Int> = linkedMapOf(
        "binding.core" to 2,
        "collection.conditional" to 2,
        "collection.grouped_sections" to 1,
        "collection.repeat" to 2,
        "content.asset_image" to 2,
        "content.badge" to 1,
        "content.bar_chart" to 2,
        "content.donut_chart" to 2,
        "content.icon" to 2,
        "content.line_chart" to 2,
        "content.marquee" to 1,
        "content.progress" to 2,
        "content.qr_code" to 1,
        "content.text" to 1,
        "format.typed" to 2,
        "layout.box" to 1,
        "layout.column" to 1,
        "layout.divider" to 1,
        "layout.grid" to 1,
        "layout.row" to 1,
        "layout.spacer" to 1,
        "layout.stack" to 1,
        "layout.surface" to 1,
        "playback.auto_skip" to 1,
        "selection.relative_date" to 1,
        "selection.temporal" to 1,
    )
}
