import { AlertCircle, Check, Info, Trash2 } from "lucide-react";
import type { ReactNode } from "react";
import { Button, Drawer, Field, Select } from "../legacy-ui";
import type { PlaylistItem, PlaylistItemInput } from "../../api/types";
import {
  itemInput,
  playlistItemUsesFixedDuration,
  transitionLabel,
} from "./playlistEditorModel";

export function PlaylistItemInspector({
  item,
  index,
  canManage,
  playlistTransition,
  saving,
  error,
  onClose,
  onChange,
  onDelete,
}: {
  item: PlaylistItem;
  index: number;
  canManage: boolean;
  playlistTransition: PlaylistItem["transition"] | "mixed";
  saving: boolean;
  error?: string;
  onClose: () => void;
  onChange: (input: PlaylistItemInput) => void;
  onDelete: () => void;
}) {
  const usesPlayerDefaults = item.usePlayerDefaults === true;
  const editable = canManage && !item.dynamic;
  const set = <K extends keyof PlaylistItemInput>(
    key: K,
    value: PlaylistItemInput[K],
  ) => onChange({ ...itemInput(item), [key]: value });

  const handlePlayerDefaultsChange = (enabled: boolean) => {
    onChange({
      ...itemInput(item),
      usePlayerDefaults: enabled,
      durationMs:
        item.assetType === "image" && enabled
          ? undefined
          : item.assetType === "image" && !enabled
            ? (item.durationMs ?? 10_000)
            : item.durationMs,
    });
  };

  return (
    <Drawer
      title={item.assetName}
      eyebrow={`Item ${index + 1} · ${item.assetType}`}
      onClose={onClose}
      closeLabel="Close item inspector"
      className="playlist-item-inspector"
      footer={
        <div className="playlist-item-inspector__footer-actions">
          {editable && (
            <Button
              variant="danger"
              onClick={() => {
                if (confirm(`Remove ${item.assetName} from this playlist?`)) {
                  onDelete();
                }
              }}
            >
              <Trash2 size={15} aria-hidden="true" />
              Remove item
            </Button>
          )}
          <Button variant="quiet" onClick={onClose}>
            Done
          </Button>
        </div>
      }
    >
      <div className="playlist-item-inspector__content">
        {item.dynamic && (
          <div
            className="playlist-editor-notice playlist-editor-notice--info"
            role="note"
          >
            <Info size={16} aria-hidden="true" />
            <span>
              This item is generated by the playlist’s tags. Edit the tag rule
              in Playlist details to change it.
            </span>
          </div>
        )}
        {error && (
          <div
            className="playlist-editor-notice playlist-editor-notice--error"
            role="alert"
          >
            <AlertCircle size={16} aria-hidden="true" />
            <span>{error}</span>
          </div>
        )}
        {saving && (
          <div className="playlist-item-inspector__saving" role="status">
            <span className="playlist-item-inspector__saving-icon">
              <Check size={13} aria-hidden="true" />
            </span>
            Saving changes…
          </div>
        )}

        <InspectorSection title="Playback">
          {(item.assetType === "image" || item.assetType === "video") && (
            <label className="playlist-inspector-switch">
              <input
                type="checkbox"
                checked={usesPlayerDefaults}
                disabled={!editable}
                onChange={(event) =>
                  handlePlayerDefaultsChange(event.target.checked)
                }
              />
              <span>
                <strong>Use Player defaults</strong>
                <small>
                  Let the assigned Player decide fit, transition, audio, and
                  volume.
                </small>
              </span>
            </label>
          )}
          <Field
            label="Transition"
            description={
              usesPlayerDefaults
                ? "Turn off Player defaults to set an item override."
                : playlistTransition !== "mixed" &&
                    item.transition !== playlistTransition
                  ? `Overrides playlist: ${transitionLabel(playlistTransition)}`
                  : "This item follows the playlist transition."
            }
          >
            <Select
              aria-label="Item transition"
              disabled={!editable || usesPlayerDefaults}
              value={item.transition}
              onChange={(event) => {
                const value = event.target.value;
                if (
                  value === "none" ||
                  value === "fade" ||
                  value === "crossfade"
                ) {
                  set("transition", value);
                }
              }}
            >
              <option value="none">None</option>
              <option value="fade">Fade</option>
              <option value="crossfade">Crossfade</option>
            </Select>
          </Field>
          {item.transition === "crossfade" && (
            <p className="playlist-inspector__help">
              Visual content blends while audio changes at the normal item
              boundary.
            </p>
          )}
          <Field label="Fit">
            <Select
              aria-label="Item fit mode"
              disabled={!editable || usesPlayerDefaults}
              value={item.fitMode}
              onChange={(event) =>
                set("fitMode", event.target.value as PlaylistItem["fitMode"])
              }
            >
              <option value="contain">Contain</option>
              <option value="cover">Cover</option>
              <option value="stretch">Stretch</option>
            </Select>
          </Field>
          <Field label="Delivery">
            <Select
              aria-label="Item delivery policy"
              disabled={!editable}
              value={item.deliveryPolicy}
              onChange={(event) =>
                set(
                  "deliveryPolicy",
                  event.target.value as PlaylistItem["deliveryPolicy"],
                )
              }
            >
              {item.assetType === "widget" || item.assetType === "layout" ? (
                <option value="stream">Stream</option>
              ) : (
                <>
                  <option value="download">Download</option>
                  <option value="stream">Stream</option>
                  <option value="automatic">Automatic</option>
                </>
              )}
            </Select>
          </Field>
        </InspectorSection>

        <InspectorSection title="Duration">
          {item.assetType === "layout" ? (
            <SecondsField
              label="Layout duration"
              value={item.durationMs ?? 30_000}
              disabled={!editable}
              onChange={(value) => set("durationMs", value)}
            />
          ) : item.assetType === "widget" &&
            item.widgetProvider === "youtube" ? (
            <>
              <Field label="Playback behavior">
                <Select
                  aria-label="Widget playback behavior"
                  disabled={!editable}
                  value={
                    item.durationMs == null ? "until_end" : "fixed_duration"
                  }
                  onChange={(event) =>
                    set(
                      "durationMs",
                      event.target.value === "until_end" ? undefined : 30_000,
                    )
                  }
                >
                  <option value="until_end">Play until video ends</option>
                  <option value="fixed_duration">
                    Play for a fixed duration
                  </option>
                </Select>
              </Field>
              {item.durationMs != null && (
                <SecondsField
                  label="Fixed duration"
                  value={item.durationMs}
                  disabled={!editable}
                  onChange={(value) => set("durationMs", value)}
                />
              )}
            </>
          ) : playlistItemUsesFixedDuration(item) ? (
            <SecondsField
              label={item.assetType === "image" ? "Image duration" : "Duration"}
              value={
                item.durationMs ??
                (item.assetType === "widget" ? 30_000 : 10_000)
              }
              disabled={!editable || usesPlayerDefaults}
              readOnly={item.assetType === "image" && usesPlayerDefaults}
              onChange={(value) => set("durationMs", value)}
            />
          ) : (
            <div className="playlist-inspector__two-column">
              <SecondsField
                label="Start"
                value={item.videoStartOffsetMs ?? 0}
                disabled={!editable || usesPlayerDefaults}
                onChange={(value) => set("videoStartOffsetMs", value)}
              />
              <SecondsField
                label="End"
                value={item.videoEndOffsetMs}
                disabled={!editable || usesPlayerDefaults}
                onChange={(value) => set("videoEndOffsetMs", value)}
                optional
              />
            </div>
          )}
        </InspectorSection>

        {item.assetType === "video" && (
          <InspectorSection title="Audio">
            <label className="playlist-inspector-switch playlist-inspector-switch--inline">
              <input
                type="checkbox"
                checked={item.audioEnabled}
                disabled={!editable || usesPlayerDefaults}
                onChange={(event) => set("audioEnabled", event.target.checked)}
              />
              <span>
                <strong>Audio enabled</strong>
              </span>
            </label>
            <Field label="Volume">
              <div className="playlist-inspector__range">
                <input
                  aria-label="Item volume"
                  type="range"
                  min="0"
                  max="1"
                  step="0.05"
                  value={item.volume}
                  disabled={!editable || usesPlayerDefaults}
                  onChange={(event) =>
                    set("volume", Number(event.target.value))
                  }
                />
                <output>{Math.round(item.volume * 100)}%</output>
              </div>
            </Field>
          </InspectorSection>
        )}

        {(item.availableFrom || item.expiresAt) && (
          <InspectorSection title="Availability">
            <dl className="playlist-inspector__metadata">
              {item.availableFrom && (
                <>
                  <dt>Available from</dt>
                  <dd>{new Date(item.availableFrom).toLocaleString()}</dd>
                </>
              )}
              {item.expiresAt && (
                <>
                  <dt>Expires</dt>
                  <dd>{new Date(item.expiresAt).toLocaleString()}</dd>
                </>
              )}
            </dl>
          </InspectorSection>
        )}
      </div>
    </Drawer>
  );
}

function InspectorSection({
  title,
  children,
}: {
  title: string;
  children: ReactNode;
}) {
  return (
    <section className="playlist-inspector-section">
      <h3>{title}</h3>
      <div className="playlist-inspector-section__body">{children}</div>
    </section>
  );
}

function SecondsField({
  label,
  value,
  disabled,
  readOnly = false,
  optional = false,
  onChange,
}: {
  label: string;
  value?: number;
  disabled: boolean;
  readOnly?: boolean;
  optional?: boolean;
  onChange: (value: number | undefined) => void;
}) {
  return (
    <Field label={`${label}${optional ? " (optional)" : ""}`}>
      {readOnly ? (
        <span className="playlist-editor__readout">Player defaults</span>
      ) : (
        <div className="playlist-inspector__duration-input">
          <input
            aria-label={`${label} in seconds`}
            type="number"
            min="0"
            step="0.1"
            disabled={disabled}
            value={value == null ? "" : value / 1000}
            onChange={(event) => {
              if (!event.target.value) {
                onChange(undefined);
                return;
              }
              const seconds = Number(event.target.value);
              if (Number.isFinite(seconds) && seconds >= 0) {
                onChange(Math.round(seconds * 1000));
              }
            }}
          />
          <span>seconds</span>
        </div>
      )}
    </Field>
  );
}
