import { Info, SlidersHorizontal } from "lucide-react";
import { useEffect, useState } from "react";
import { Button, Field, Select } from "../legacy-ui";
import type { PlaylistItem } from "../../api/types";
import {
  type ImageDurationSummary,
  type PlaylistTransition,
  transitionLabel,
} from "./playlistEditorModel";

export function PlaylistPlaybackDefaults({
  items,
  sourceType,
  canManage,
  transition,
  imageDuration,
  transitionPending,
  imageDurationPending,
  onTransitionChange,
  onImageDurationChange,
  onOpenDetails,
}: {
  items: PlaylistItem[];
  sourceType: "static" | "tag";
  canManage: boolean;
  transition: PlaylistTransition;
  imageDuration: ImageDurationSummary;
  transitionPending: boolean;
  imageDurationPending: boolean;
  onTransitionChange: (value: PlaylistItem["transition"]) => void;
  onImageDurationChange: (seconds: number) => void;
  onOpenDetails: () => void;
}) {
  const tagDriven = sourceType === "tag";
  const hasImages = items.some((item) => item.assetType === "image");
  const transitionValue = transition === "mixed" ? "mixed" : transition;
  const [durationDraft, setDurationDraft] = useState("");

  useEffect(() => {
    setDurationDraft(
      imageDuration.kind === "value" ? String(imageDuration.seconds) : "",
    );
  }, [imageDuration]);

  const commitImageDuration = () => {
    const value = Number(durationDraft);
    if (Number.isFinite(value) && value > 0) {
      onImageDurationChange(value);
    }
  };

  return (
    <section
      className="playlist-playback"
      aria-labelledby="playlist-playback-title"
    >
      <div className="playlist-playback__header">
        <div>
          <p className="playlist-editor-eyebrow">Playback</p>
          <h2 id="playlist-playback-title">Playback defaults</h2>
          <p>
            Use these controls for common authoring changes. Individual items
            can still be customized from the timeline.
          </p>
        </div>
        <Button variant="quiet" compact onClick={onOpenDetails}>
          <SlidersHorizontal size={14} aria-hidden="true" />
          More settings
        </Button>
      </div>

      <div className="playlist-playback__controls">
        <Field
          label="Transition"
          description={
            tagDriven
              ? "Tag-driven items are generated by the tag rule."
              : "Applies to every item and creates an item-level override."
          }
        >
          <Select
            aria-label="Playlist transition"
            disabled={
              !canManage || tagDriven || transitionPending || !items.length
            }
            value={transitionValue}
            onChange={(event) => {
              const value = event.target.value;
              if (
                value === "none" ||
                value === "fade" ||
                value === "crossfade"
              ) {
                onTransitionChange(value);
              }
            }}
          >
            {transition === "mixed" && <option value="mixed">Mixed</option>}
            <option value="none">None</option>
            <option value="fade">Fade</option>
            <option value="crossfade">Crossfade</option>
          </Select>
        </Field>

        <Field
          label="Image duration"
          description={
            tagDriven
              ? "Controlled by the tag rule."
              : imageDuration.kind === "player"
                ? "Set a fixed duration for image items."
                : "Updates fixed-duration image items."
          }
        >
          {!hasImages ? (
            <span className="playlist-editor__readout">No image items</span>
          ) : (
            <div className="playlist-playback__duration-control">
              <input
                aria-label="Playlist image duration in seconds"
                type="number"
                min="1"
                max="86400"
                disabled={!canManage || tagDriven || imageDurationPending}
                value={durationDraft}
                placeholder={
                  imageDuration.kind === "mixed" ? "Mixed" : "Player defaults"
                }
                onChange={(event) => {
                  setDurationDraft(event.target.value);
                }}
                onBlur={commitImageDuration}
                onKeyDown={(event) => {
                  if (event.key === "Enter") {
                    event.preventDefault();
                    commitImageDuration();
                    event.currentTarget.blur();
                  }
                }}
              />
              <span>seconds</span>
            </div>
          )}
        </Field>
      </div>

      <div className="playlist-playback__note" role="note">
        <Info size={15} aria-hidden="true" />
        <span>
          {transition === "crossfade"
            ? "Crossfade blends visual content while audio changes at the normal item boundary."
            : `Current transition: ${transitionLabel(transition)}.`}
          {!tagDriven && " Changes save automatically."}
        </span>
      </div>
    </section>
  );
}
