import { AlertCircle, Check, Info, Trash2 } from "lucide-react";
import { useState, type ReactNode } from "react";
import type { PlaylistItem, PlaylistItemInput } from "../../api/types";
import {
  AlertDialog as RheaAlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "../ui/alert-dialog";
import { Alert, AlertDescription, AlertTitle } from "../ui/alert";
import { Button as RheaButton } from "../ui/button";
import { Field, FieldDescription, FieldLabel } from "../ui/field";
import {
  InputGroup,
  InputGroupAddon,
  InputGroupInput,
} from "../ui/input-group";
import {
  Select as RheaSelect,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "../ui/select";
import {
  Sheet as RheaSheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
} from "../ui/sheet";
import { Slider as RheaSlider } from "../ui/slider";
import { Switch as RheaSwitch } from "../ui/switch";
import { optionLabel } from "../../content/data-sources/shared";
import {
  itemInput,
  playlistItemUsesFixedDuration,
  transitionLabel,
} from "./playlistEditorModel";

const itemTransitionOptions = [
  { value: "none", label: "None" },
  { value: "fade", label: "Fade" },
  { value: "crossfade", label: "Crossfade" },
];

const fitModeOptions = [
  { value: "contain", label: "Contain" },
  { value: "cover", label: "Cover" },
  { value: "stretch", label: "Stretch" },
];

const deliveryOptions = [
  { value: "download", label: "Download" },
  { value: "stream", label: "Stream" },
  { value: "automatic", label: "Automatic" },
];

const widgetBehaviorOptions = [
  { value: "until_end", label: "Play until video ends" },
  { value: "fixed_duration", label: "Play for a fixed duration" },
];

export function PlaylistItemInspector({
  item,
  index,
  canManage,
  playlistTransition,
  saving,
  error,
  onClose,
  onChange,
  onDelete,
}: InspectorProps) {
  return (
    <RheaSheet
      open
      onOpenChange={(open) => {
        if (!open) onClose();
      }}
    >
      <SheetContent side="right" className="overflow-y-auto">
        <SheetHeader>
          <p className="text-xs font-medium tracking-wide text-muted-foreground uppercase">
            {`Item ${index + 1} · ${item.assetType}`}
          </p>
          <SheetTitle>{item.assetName}</SheetTitle>
        </SheetHeader>
        <div className="px-4">
          <PlaylistItemInspectorBody
            item={item}
            index={index}
            canManage={canManage}
            playlistTransition={playlistTransition}
            saving={saving}
            error={error}
            onClose={onClose}
            onChange={onChange}
            onDelete={onDelete}
          />
        </div>
      </SheetContent>
    </RheaSheet>
  );
}

type InspectorProps = {
  item: PlaylistItem;
  index: number;
  canManage: boolean;
  playlistTransition: PlaylistItem["transition"] | "mixed";
  saving: boolean;
  error?: string;
  onClose: () => void;
  onChange: (input: PlaylistItemInput) => void;
  onDelete: () => void;
};

// PlaylistItemInspectorBody is the Sheet-free inspector content. The playlist
// editor renders it inline in the desktop inspector pane and inside the Sheet
// above on narrow screens.
export function PlaylistItemInspectorBody({
  item,
  canManage,
  playlistTransition,
  saving,
  error,
  onClose,
  onChange,
  onDelete,
}: InspectorProps) {
  const usesPlayerDefaults = item.usePlayerDefaults === true;
  const editable = canManage && !item.dynamic;
  const [confirmingDelete, setConfirmingDelete] = useState(false);
  const set = <K extends keyof PlaylistItemInput>(
    key: K,
    value: PlaylistItemInput[K],
  ) => onChange({ ...itemInput(item), [key]: value });

  const handlePlayerDefaultsChange = (enabled: boolean) => {
    onChange({
      ...itemInput(item),
      usePlayerDefaults: enabled,
      durationMs:
        item.assetType === "image" && enabled
          ? undefined
          : item.assetType === "image" && !enabled
            ? (item.durationMs ?? 10_000)
            : item.durationMs,
    });
  };

  return (
    <>
      <div className="grid gap-6">
        {item.dynamic && (
          <Alert>
            <Info size={16} aria-hidden="true" />
            <AlertDescription>
              This item is generated by the playlist’s tags. Edit the tag rule
              in Playlist details to change it.
            </AlertDescription>
          </Alert>
        )}
        {error && (
          <Alert variant="destructive">
            <AlertCircle size={16} aria-hidden="true" />
            <AlertTitle>Could not save this item</AlertTitle>
            <AlertDescription>{error}</AlertDescription>
          </Alert>
        )}
        {saving && (
          <div
            className="flex items-center gap-2 text-sm text-muted-foreground"
            role="status"
          >
            <Check size={13} aria-hidden="true" />
            Saving changes…
          </div>
        )}

        <InspectorSection title="Playback">
          {(item.assetType === "image" || item.assetType === "video") && (
            // The wrapping label names the switch; no extra aria-label.
            <label className="flex items-start gap-2 text-sm">
              <RheaSwitch
                checked={usesPlayerDefaults}
                disabled={!editable}
                onCheckedChange={(checked) =>
                  handlePlayerDefaultsChange(checked === true)
                }
                className="mt-0.5"
              />
              <span className="grid gap-0.5">
                <strong className="font-medium">Use Player defaults</strong>
                <small className="text-xs text-muted-foreground">
                  Let the assigned Player decide fit, transition, audio, and
                  volume.
                </small>
              </span>
            </label>
          )}
          <Field>
            <FieldLabel htmlFor="inspector-transition">Transition</FieldLabel>
            <RheaSelect
              disabled={!editable || usesPlayerDefaults}
              value={item.transition}
              onValueChange={(next) => {
                if (
                  next === "none" ||
                  next === "fade" ||
                  next === "crossfade"
                ) {
                  set("transition", next);
                }
              }}
            >
              <SelectTrigger
                id="inspector-transition"
                aria-label="Item transition"
              >
                <SelectValue>
                  {optionLabel(itemTransitionOptions, item.transition)}
                </SelectValue>
              </SelectTrigger>
              <SelectContent>
                {itemTransitionOptions.map((option) => (
                  <SelectItem key={option.value} value={option.value}>
                    {option.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </RheaSelect>
            <FieldDescription>
              {usesPlayerDefaults
                ? "Turn off Player defaults to set an item override."
                : playlistTransition !== "mixed" &&
                    item.transition !== playlistTransition
                  ? `Overrides playlist: ${transitionLabel(playlistTransition)}`
                  : "This item follows the playlist transition."}
            </FieldDescription>
          </Field>
          {item.transition === "crossfade" && (
            <p className="text-xs text-muted-foreground">
              Visual content blends while audio changes at the normal item
              boundary.
            </p>
          )}
          <Field>
            <FieldLabel htmlFor="inspector-fit">Fit</FieldLabel>
            <RheaSelect
              disabled={!editable || usesPlayerDefaults}
              value={item.fitMode}
              onValueChange={(next) =>
                set("fitMode", next as PlaylistItem["fitMode"])
              }
            >
              <SelectTrigger id="inspector-fit" aria-label="Item fit mode">
                <SelectValue>
                  {optionLabel(fitModeOptions, item.fitMode)}
                </SelectValue>
              </SelectTrigger>
              <SelectContent>
                {fitModeOptions.map((option) => (
                  <SelectItem key={option.value} value={option.value}>
                    {option.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </RheaSelect>
          </Field>
          <Field>
            <FieldLabel htmlFor="inspector-delivery">Delivery</FieldLabel>
            <RheaSelect
              disabled={!editable}
              value={item.deliveryPolicy}
              onValueChange={(next) =>
                set("deliveryPolicy", next as PlaylistItem["deliveryPolicy"])
              }
            >
              <SelectTrigger
                id="inspector-delivery"
                aria-label="Item delivery policy"
              >
                <SelectValue>
                  {optionLabel(
                    item.assetType === "widget" || item.assetType === "layout"
                      ? deliveryOptions.filter(
                          (option) => option.value === "stream",
                        )
                      : deliveryOptions,
                    item.deliveryPolicy,
                  )}
                </SelectValue>
              </SelectTrigger>
              <SelectContent>
                {item.assetType === "widget" || item.assetType === "layout" ? (
                  <SelectItem value="stream">Stream</SelectItem>
                ) : (
                  deliveryOptions.map((option) => (
                    <SelectItem key={option.value} value={option.value}>
                      {option.label}
                    </SelectItem>
                  ))
                )}
              </SelectContent>
            </RheaSelect>
          </Field>
        </InspectorSection>

        <InspectorSection title="Duration">
          {item.assetType === "layout" ? (
            <SecondsField
              label="Layout duration"
              value={item.durationMs ?? 30_000}
              disabled={!editable}
              onChange={(value) => set("durationMs", value)}
            />
          ) : item.assetType === "widget" &&
            item.widgetProvider === "youtube" ? (
            <>
              <Field>
                <FieldLabel htmlFor="inspector-widget-behavior">
                  Playback behavior
                </FieldLabel>
                <RheaSelect
                  disabled={!editable}
                  value={
                    item.durationMs == null ? "until_end" : "fixed_duration"
                  }
                  onValueChange={(next) =>
                    set("durationMs", next === "until_end" ? undefined : 30_000)
                  }
                >
                  <SelectTrigger
                    id="inspector-widget-behavior"
                    aria-label="Widget playback behavior"
                  >
                    <SelectValue>
                      {optionLabel(
                        widgetBehaviorOptions,
                        item.durationMs == null
                          ? "until_end"
                          : "fixed_duration",
                      )}
                    </SelectValue>
                  </SelectTrigger>
                  <SelectContent>
                    {widgetBehaviorOptions.map((option) => (
                      <SelectItem key={option.value} value={option.value}>
                        {option.label}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </RheaSelect>
              </Field>
              {item.durationMs != null && (
                <SecondsField
                  label="Fixed duration"
                  value={item.durationMs}
                  disabled={!editable}
                  onChange={(value) => set("durationMs", value)}
                />
              )}
            </>
          ) : playlistItemUsesFixedDuration(item) ? (
            <SecondsField
              label={item.assetType === "image" ? "Image duration" : "Duration"}
              value={
                item.durationMs ??
                (item.assetType === "widget" ? 30_000 : 10_000)
              }
              disabled={!editable || usesPlayerDefaults}
              readOnly={item.assetType === "image" && usesPlayerDefaults}
              onChange={(value) => set("durationMs", value)}
            />
          ) : (
            <div className="grid gap-4 sm:grid-cols-2">
              <SecondsField
                label="Start"
                value={item.videoStartOffsetMs ?? 0}
                disabled={!editable || usesPlayerDefaults}
                onChange={(value) => set("videoStartOffsetMs", value)}
              />
              <SecondsField
                label="End"
                value={item.videoEndOffsetMs}
                disabled={!editable || usesPlayerDefaults}
                onChange={(value) => set("videoEndOffsetMs", value)}
                optional
              />
            </div>
          )}
        </InspectorSection>

        {item.assetType === "video" && (
          <InspectorSection title="Audio">
            {/* The wrapping label names the switch; no extra aria-label. */}
            <label className="flex items-center gap-2 text-sm">
              <RheaSwitch
                checked={item.audioEnabled}
                disabled={!editable || usesPlayerDefaults}
                onCheckedChange={(checked) =>
                  set("audioEnabled", checked === true)
                }
              />
              <span className="font-medium">Audio enabled</span>
            </label>
            <Field>
              <FieldLabel htmlFor="inspector-volume">Volume</FieldLabel>
              <div className="flex items-center gap-3">
                <RheaSlider
                  id="inspector-volume"
                  aria-label="Item volume"
                  min={0}
                  max={1}
                  step={0.05}
                  value={[item.volume]}
                  disabled={!editable || usesPlayerDefaults}
                  onValueChange={(next) =>
                    set(
                      "volume",
                      Number(Array.isArray(next) ? (next[0] ?? 0) : next),
                    )
                  }
                  className="flex-1"
                />
                <output className="w-12 shrink-0 text-right text-sm tabular-nums">
                  {Math.round(item.volume * 100)}%
                </output>
              </div>
            </Field>
          </InspectorSection>
        )}

        {(item.availableFrom || item.expiresAt) && (
          <InspectorSection title="Availability">
            <dl className="grid gap-1 text-sm">
              {item.availableFrom && (
                <>
                  <dt className="text-muted-foreground">Available from</dt>
                  <dd>{new Date(item.availableFrom).toLocaleString()}</dd>
                </>
              )}
              {item.expiresAt && (
                <>
                  <dt className="text-muted-foreground">Expires</dt>
                  <dd>{new Date(item.expiresAt).toLocaleString()}</dd>
                </>
              )}
            </dl>
          </InspectorSection>
        )}
      </div>
      <div className="flex flex-wrap gap-2">
        {editable && (
          <RheaButton
            type="button"
            variant="destructive"
            onClick={() => setConfirmingDelete(true)}
          >
            <Trash2 size={15} aria-hidden="true" />
            Remove item
          </RheaButton>
        )}
        <RheaButton type="button" variant="outline" onClick={onClose}>
          Done
        </RheaButton>
      </div>
      <RheaAlertDialog
        open={confirmingDelete}
        onOpenChange={(open) => {
          if (!open) setConfirmingDelete(false);
        }}
      >
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>
              Remove {item.assetName} from this playlist?
            </AlertDialogTitle>
            <AlertDialogDescription>
              The item leaves the timeline but its media stays in the library.
              This cannot be undone.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction
              onClick={() => {
                setConfirmingDelete(false);
                onDelete();
              }}
            >
              Remove item
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </RheaAlertDialog>
    </>
  );
}

function InspectorSection({
  title,
  children,
}: {
  title: string;
  children: ReactNode;
}) {
  return (
    <section className="grid gap-3">
      <h3 className="text-sm font-medium">{title}</h3>
      <div className="grid gap-3">{children}</div>
    </section>
  );
}

function SecondsField({
  label,
  value,
  disabled,
  readOnly = false,
  optional = false,
  onChange,
}: {
  label: string;
  value?: number;
  disabled: boolean;
  readOnly?: boolean;
  optional?: boolean;
  onChange: (value: number | undefined) => void;
}) {
  const fieldId = `inspector-seconds-${label.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`;
  return (
    <Field>
      <FieldLabel htmlFor={fieldId}>
        {label}
        {optional ? " (optional)" : ""}
      </FieldLabel>
      {readOnly ? (
        <span className="text-sm text-muted-foreground">Player defaults</span>
      ) : (
        <InputGroup className="w-36">
          <InputGroupInput
            id={fieldId}
            aria-label={`${label} in seconds`}
            type="number"
            min="0"
            step="0.1"
            disabled={disabled}
            value={value == null ? "" : value / 1000}
            onChange={(event) => {
              if (!event.target.value) {
                onChange(undefined);
                return;
              }
              const seconds = Number(event.target.value);
              if (Number.isFinite(seconds) && seconds >= 0) {
                onChange(Math.round(seconds * 1000));
              }
            }}
          />
          <InputGroupAddon align="inline-end">
            <span aria-hidden="true">s</span>
          </InputGroupAddon>
        </InputGroup>
      )}
    </Field>
  );
}
