import { Info, SlidersHorizontal } from "lucide-react";
import { useEffect, useState } from "react";
import type { PlaylistItem } from "../../api/types";
import { Button as RheaButton } from "../ui/button";
import { Field, FieldDescription, FieldLabel } from "../ui/field";
import {
  InputGroup,
  InputGroupAddon,
  InputGroupInput,
} from "../ui/input-group";
import {
  Select as RheaSelect,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "../ui/select";
import {
  type ImageDurationSummary,
  type PlaylistTransition,
  transitionLabel,
} from "./playlistEditorModel";

const transitionOptions = [
  { value: "mixed", label: "Mixed" },
  { value: "none", label: "None" },
  { value: "fade", label: "Fade" },
  { value: "crossfade", label: "Crossfade" },
];

export function PlaylistPlaybackDefaults({
  items,
  sourceType,
  canManage,
  transition,
  imageDuration,
  transitionPending,
  imageDurationPending,
  onTransitionChange,
  onImageDurationChange,
  onOpenDetails,
}: {
  items: PlaylistItem[];
  sourceType: "static" | "tag";
  canManage: boolean;
  transition: PlaylistTransition;
  imageDuration: ImageDurationSummary;
  transitionPending: boolean;
  imageDurationPending: boolean;
  onTransitionChange: (value: PlaylistItem["transition"]) => void;
  onImageDurationChange: (seconds: number) => void;
  onOpenDetails: () => void;
}) {
  const tagDriven = sourceType === "tag";
  const hasImages = items.some((item) => item.assetType === "image");
  const transitionValue = transition === "mixed" ? "mixed" : transition;
  const [durationDraft, setDurationDraft] = useState("");

  useEffect(() => {
    setDurationDraft(
      imageDuration.kind === "value" ? String(imageDuration.seconds) : "",
    );
  }, [imageDuration]);

  const commitImageDuration = () => {
    const value = Number(durationDraft);
    if (Number.isFinite(value) && value > 0) {
      onImageDurationChange(value);
    }
  };

  return (
    <section aria-labelledby="playlist-playback-title" className="grid gap-4">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div className="grid min-w-0 gap-1">
          <p className="text-xs font-medium tracking-wide text-muted-foreground uppercase">
            Playback
          </p>
          <h2
            id="playlist-playback-title"
            className="text-lg font-semibold tracking-tight"
          >
            Playback defaults
          </h2>
          <p className="text-sm text-muted-foreground">
            Use these controls for common authoring changes. Individual items
            can still be customized from the timeline.
          </p>
        </div>
        <RheaButton
          type="button"
          variant="ghost"
          size="sm"
          onClick={onOpenDetails}
        >
          <SlidersHorizontal size={14} aria-hidden="true" />
          More settings
        </RheaButton>
      </div>

      <div className="grid gap-4 sm:grid-cols-2">
        <Field>
          <FieldLabel htmlFor="playlist-transition">Transition</FieldLabel>
          <RheaSelect
            disabled={
              !canManage || tagDriven || transitionPending || !items.length
            }
            value={transitionValue}
            onValueChange={(next) => {
              if (next === "none" || next === "fade" || next === "crossfade") {
                onTransitionChange(next);
              }
            }}
            items={transitionOptions}
          >
            <SelectTrigger
              id="playlist-transition"
              aria-label="Playlist transition"
            >
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {transition === "mixed" && (
                <SelectItem value="mixed">Mixed</SelectItem>
              )}
              <SelectItem value="none">None</SelectItem>
              <SelectItem value="fade">Fade</SelectItem>
              <SelectItem value="crossfade">Crossfade</SelectItem>
            </SelectContent>
          </RheaSelect>
          <FieldDescription>
            {tagDriven
              ? "Tag-driven items are generated by the tag rule."
              : "Applies to every item and creates an item-level override."}
          </FieldDescription>
        </Field>

        <Field>
          <FieldLabel htmlFor="playlist-image-duration">
            Image duration
          </FieldLabel>
          {!hasImages ? (
            <span className="text-sm text-muted-foreground">
              No image items
            </span>
          ) : (
            <InputGroup className="w-40">
              <InputGroupInput
                id="playlist-image-duration"
                aria-label="Playlist image duration in seconds"
                type="number"
                min="1"
                max="86400"
                disabled={!canManage || tagDriven || imageDurationPending}
                value={durationDraft}
                placeholder={
                  imageDuration.kind === "mixed" ? "Mixed" : "Player defaults"
                }
                onChange={(event) => {
                  setDurationDraft(event.target.value);
                }}
                onBlur={commitImageDuration}
                onKeyDown={(event) => {
                  if (event.key === "Enter") {
                    event.preventDefault();
                    commitImageDuration();
                    event.currentTarget.blur();
                  }
                }}
              />
              <InputGroupAddon align="inline-end">
                <span aria-hidden="true">s</span>
              </InputGroupAddon>
            </InputGroup>
          )}
          <FieldDescription>
            {tagDriven
              ? "Controlled by the tag rule."
              : imageDuration.kind === "player"
                ? "Set a fixed duration for image items."
                : "Updates fixed-duration image items."}
          </FieldDescription>
        </Field>
      </div>

      <div
        className="flex items-start gap-2 rounded-lg bg-muted p-3 text-sm text-muted-foreground"
        role="note"
      >
        <Info size={15} aria-hidden="true" className="mt-0.5 shrink-0" />
        <span>
          {transition === "crossfade"
            ? "Crossfade blends visual content while audio changes at the normal item boundary."
            : `Current transition: ${transitionLabel(transition)}.`}
          {!tagDriven && " Changes save automatically."}
        </span>
      </div>
    </section>
  );
}
