/**
 * Review routing. A plugin's maintainers are subject-matter stewards: anyone
 * may change any plugin, and core maintainers keep merge authority. GitHub
 * only requests review from a CODEOWNERS handle that has write access, so the
 * generated file lists the eligible maintainers and names the others in a
 * comment. Eligibility never changes who a plugin's maintainers are.
 */
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import type { Problem, Repo } from "./repo.ts";

export const CODEOWNERS = ".github/CODEOWNERS";
export const REVIEW_ELIGIBILITY = "plugins/review-eligibility.json";

export function eligibleReviewers(repo: Repo): {
  handles: Set<string>;
  problems: Problem[];
} {
  const path = join(repo.root, REVIEW_ELIGIBILITY);
  if (!existsSync(path)) {
    return {
      handles: new Set(),
      problems: [{ file: REVIEW_ELIGIBILITY, message: "file is missing" }],
    };
  }
  const parsed = JSON.parse(readFileSync(path, "utf8")) as {
    eligible?: unknown;
  };
  if (
    !Array.isArray(parsed.eligible) ||
    !parsed.eligible.every((item) => typeof item === "string")
  ) {
    return {
      handles: new Set(),
      problems: [
        {
          file: REVIEW_ELIGIBILITY,
          message: '"eligible" must be a list of handles',
        },
      ],
    };
  }
  return {
    handles: new Set(parsed.eligible.map((handle) => handle.toLowerCase())),
    problems: [],
  };
}

export function codeownersFile(repo: Repo, eligible: Set<string>): string {
  const lines = [
    "# Generated by pluginctl from each plugin's tilecast.plugin.json maintainers.",
    "# Do not edit: change the manifest and run `npm run plugins:generate`.",
    "#",
    "# Maintainers are stewards, not gatekeepers. This file only requests their",
    "# review; branch protection does not require code-owner approval, and core",
    "# maintainers keep architecture and merge authority. A maintainer without",
    `# repository write access is listed in a comment (see ${REVIEW_ELIGIBILITY}).`,
    "",
  ];
  for (const plugin of repo.plugins) {
    const owners = plugin.manifest.maintainers.filter((handle) =>
      eligible.has(handle.toLowerCase()),
    );
    const others = plugin.manifest.maintainers.filter(
      (handle) => !eligible.has(handle.toLowerCase()),
    );
    if (others.length > 0) {
      lines.push(
        `# ${plugin.manifest.id}: also maintained by ${others.join(" ")}`,
      );
    }
    if (owners.length > 0) {
      lines.push(`/plugins/${plugin.dir}/ ${owners.join(" ")}`);
    } else {
      lines.push(
        `# /plugins/${plugin.dir}/ has no maintainer eligible for review requests`,
      );
    }
  }
  return lines.join("\n") + "\n";
}
