/**
 * Generated artifacts. Only what a toolchain cannot discover by itself is
 * generated: Go has no compile-time glob import, GitHub reads one CODEOWNERS
 * file, and OpenAPI consumers read one document. Studio and the Player
 * runtime discover plugins with Vite's import.meta.glob instead.
 */
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import * as prettier from "prettier";
import { AUTOMATION_FILENAME } from "../../src/automation.ts";
import { pluginManifestJSONSchema } from "../../src/manifest.ts";
import { resolveAutomation } from "./automation.ts";
import { codeownersFile, CODEOWNERS, eligibleReviewers } from "./codeowners.ts";
import {
  collectMigrations,
  migrationLock,
  MIGRATION_LOCK,
} from "./migrations.ts";
import { composeOpenAPI, COMPOSED_OPENAPI } from "./openapi.ts";
import type { Problem, Repo } from "./repo.ts";

export const GO_REGISTRY = "plugins/registry_gen.go";
export const JSON_SCHEMA =
  "packages/plugin-sdk/schema/tilecast-plugin.schema.json";

const SDK_IMPORT = "github.com/tilecast/tilecast/packages/plugin-sdk/go/plugin";

export function goRegistry(repo: Repo): string {
  const servers = repo.plugins.filter((plugin) => plugin.goPackage);
  const imports = [
    { path: SDK_IMPORT, alias: "" },
    ...servers.map((plugin) => ({
      path: `github.com/tilecast/tilecast/plugins/${plugin.dir}`,
      alias: plugin.goPackage!,
    })),
  ].sort((a, b) => a.path.localeCompare(b.path));
  const lines = [
    "// Code generated by pluginctl from plugins/*/tilecast.plugin.json. DO NOT EDIT.",
    "",
    "package plugins",
    "",
    "import (",
    ...imports.map(
      ({ path, alias }) => `\t${alias ? `${alias} ` : ""}"${path}"`,
    ),
    ")",
    "",
    "// Bundled returns every first-party plugin compiled into this release, in",
    "// plugin ID order. Add a plugin by adding its directory, not by editing this",
    "// list.",
    "func Bundled() []plugin.Plugin {",
    "\treturn []plugin.Plugin{",
    ...servers.map((plugin) => `\t\t${plugin.goPackage}.New(),`),
    "\t}",
    "}",
  ];
  return lines.join("\n") + "\n";
}

async function format(
  text: string,
  path: string,
  root: string,
): Promise<string> {
  const options = (await prettier.resolveConfig(join(root, path))) ?? {};
  return prettier.format(text, { ...options, filepath: join(root, path) });
}

/** Every generated file, keyed by repository-relative path. */
export async function generate(
  repo: Repo,
): Promise<{ files: Map<string, string>; problems: Problem[] }> {
  const problems: Problem[] = [];
  const files = new Map<string, string>();
  files.set(GO_REGISTRY, goRegistry(repo));

  const eligible = eligibleReviewers(repo);
  problems.push(...eligible.problems);
  files.set(CODEOWNERS, codeownersFile(repo, eligible.handles));

  files.set(
    JSON_SCHEMA,
    await format(
      JSON.stringify(pluginManifestJSONSchema()),
      JSON_SCHEMA,
      repo.root,
    ),
  );

  const openapi = composeOpenAPI(repo);
  problems.push(...openapi.problems);
  files.set(
    COMPOSED_OPENAPI,
    await format(openapi.text, COMPOSED_OPENAPI, repo.root),
  );

  const migrations = collectMigrations(repo);
  problems.push(...migrations.problems);
  files.set(
    MIGRATION_LOCK,
    await format(
      migrationLock(migrations.migrations),
      MIGRATION_LOCK,
      repo.root,
    ),
  );

  // Resolved automation documents ride into the release inside each
  // plugin directory, so the server embeds and serves them without
  // parsing YAML at runtime. Only files that validate resolve; anything
  // else is a check problem, not a silent omission.
  for (const plugin of repo.plugins) {
    const id = plugin.manifest.id;
    const automationPath = join(plugin.path, AUTOMATION_FILENAME);
    if (!existsSync(automationPath)) continue;
    const declared = plugin.manifest.api?.openapi;
    const fragmentPath =
      declared !== undefined ? join(plugin.path, declared) : null;
    const { problems: resolvedProblems, resolved } = resolveAutomation(
      id,
      readFileSync(automationPath, "utf8"),
      fragmentPath !== null && existsSync(fragmentPath)
        ? readFileSync(fragmentPath, "utf8")
        : null,
    );
    problems.push(...resolvedProblems);
    if (!resolved) continue;
    const generated = `plugins/${plugin.dir}/automation.gen.json`;
    files.set(
      generated,
      await format(JSON.stringify(resolved, null, 2), generated, repo.root),
    );
  }
  return { files, problems };
}

/** Generated files whose committed content differs from a fresh generation. */
export function stale(repo: Repo, files: Map<string, string>): string[] {
  return [...files]
    .filter(([path, content]) => {
      const full = join(repo.root, path);
      return !existsSync(full) || readFileSync(full, "utf8") !== content;
    })
    .map(([path]) => path);
}
