/**
 * OpenAPI composition. docs/openapi/core.yaml holds the core API and each
 * plugin owns a fragment next to its implementation. The composed
 * docs/openapi.yaml is Tilecast's canonical description; this module only
 * merges maps and rewrites references, it does not interpret OpenAPI.
 */
import { existsSync, readFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import YAML, { isMap, isScalar, type Document, type YAMLMap } from "yaml";
import type { Problem, Repo } from "./repo.ts";

export const CORE_OPENAPI = "docs/openapi/core.yaml";
export const COMPOSED_OPENAPI = "docs/openapi.yaml";

const COMPONENT_SECTIONS = [
  "schemas",
  "parameters",
  "responses",
  "requestBodies",
  "headers",
  "securitySchemes",
] as const;

export function composeOpenAPI(repo: Repo): {
  text: string;
  problems: Problem[];
} {
  const problems: Problem[] = [];
  const corePath = join(repo.root, CORE_OPENAPI);
  const core = YAML.parseDocument(readFileSync(corePath, "utf8"));
  const paths = core.get("paths") as YAMLMap;
  for (const plugin of repo.plugins) {
    const declared = plugin.manifest.api?.openapi;
    if (!declared) continue;
    const id = plugin.manifest.id;
    const fragmentPath = join(plugin.path, declared);
    const file = relative(repo.root, fragmentPath);
    if (!existsSync(fragmentPath)) {
      problems.push({
        plugin: id,
        file,
        message: "declared OpenAPI fragment does not exist",
      });
      continue;
    }
    const fragment = YAML.parseDocument(readFileSync(fragmentPath, "utf8"));
    if (fragment.errors.length > 0) {
      problems.push({ plugin: id, file, message: fragment.errors[0]!.message });
      continue;
    }
    rewriteCoreReferences(fragment, dirname(fragmentPath), corePath);
    const allowed = (plugin.manifest.api?.basePaths ?? []).map(
      (base) => `/api/v1${base}`,
    );
    const fragmentPaths = fragment.get("paths");
    if (isMap(fragmentPaths)) {
      for (const pair of fragmentPaths.items) {
        const key = isScalar(pair.key)
          ? String(pair.key.value)
          : String(pair.key);
        if (
          !allowed.some((base) => key === base || key.startsWith(`${base}/`))
        ) {
          problems.push({
            plugin: id,
            file,
            message: `path ${key} is outside the manifest's api.basePaths`,
          });
          continue;
        }
        if (paths.has(key)) {
          problems.push({
            plugin: id,
            file,
            message: `path ${key} is already described`,
          });
          continue;
        }
        paths.add(pair);
      }
    }
    for (const section of COMPONENT_SECTIONS) {
      const incoming = fragment.getIn(["components", section]);
      if (!isMap(incoming)) continue;
      if (!core.hasIn(["components", section])) {
        core.setIn(["components", section], core.createNode({}));
      }
      const target = core.getIn(["components", section]) as YAMLMap;
      for (const pair of incoming.items) {
        const key = isScalar(pair.key)
          ? String(pair.key.value)
          : String(pair.key);
        if (target.has(key)) {
          problems.push({
            plugin: id,
            file,
            message: `components.${section}.${key} is already defined`,
          });
          continue;
        }
        target.add(pair);
      }
    }
  }
  const header =
    "# Generated by pluginctl from docs/openapi/core.yaml and each plugin's\n" +
    "# api/openapi.yaml. Do not edit: run `npm run plugins:generate`.\n";
  return { text: header + core.toString({ lineWidth: 0 }), problems };
}

/**
 * A fragment refers to core components through the core file
 * (`../../../docs/openapi/core.yaml#/components/...`) so it stays valid on
 * its own. In the composed document those become local references.
 */
function rewriteCoreReferences(
  document: Document,
  fragmentDir: string,
  corePath: string,
) {
  YAML.visit(document, {
    Pair(_, pair) {
      if (
        !isScalar(pair.key) ||
        pair.key.value !== "$ref" ||
        !isScalar(pair.value)
      )
        return;
      const value = String(pair.value.value);
      const hash = value.indexOf("#");
      if (hash <= 0) return;
      if (resolve(fragmentDir, value.slice(0, hash)) === corePath) {
        pair.value.value = value.slice(hash);
      }
    },
  });
}
