package plugins

import (
	"context"
	"errors"

	"github.com/tilecast/tilecast/packages/plugin-sdk/go/plugin"
)

// ErrAutomationAbsent reports a known, installed plugin that maps no
// operations into operator automation. It is distinct from
// ErrPluginNotFound (the release does not know the plugin) and
// ErrPluginNotInstalled (nobody chose to add it): the plugin exists and
// runs, it simply has no automation surface.
var ErrAutomationAbsent = errors.New("plugin automation not found")

// Automation returns a known, installed plugin's resolved automation
// document. The bytes are the plugin's embedded automation.gen.json,
// generated by pluginctl from a validated automation.yaml: the host
// serves them verbatim and never parses YAML at runtime. Operator
// clients dispatch on this document without naming the plugin in their
// own source.
func (s *Service) Automation(ctx context.Context, id string) ([]byte, error) {
	hosted, ok := s.hostedPlugin(id)
	if !ok {
		return nil, ErrPluginNotFound
	}
	if err := s.RequireInstalled(ctx, id); err != nil {
		return nil, err
	}
	provider, ok := hosted.plugin.(plugin.AutomationProvider)
	if !ok {
		return nil, ErrAutomationAbsent
	}
	document, err := plugin.ParseAutomation(provider.Automation())
	if err != nil {
		return nil, err
	}
	if document.Plugin != id {
		return nil, ErrAutomationAbsent
	}
	return provider.Automation(), nil
}
