// Code generated by widgetctl from plugin-owned tilecast.widget.json files. DO NOT EDIT.
// Run `npm run widgets:generate`.

package widgets

// PluginWidgetManifest is one plugin-owned Widget manifest composed into
// the Server's content catalog. PluginID is the stable id from the owning
// plugin's tilecast.plugin.json (never the plugin directory basename),
// Dir is the Widget's directory relative to the repository root, and JSON
// carries the exact tilecast.widget.json bytes for validation and
// fingerprinting. The manifest beside the Widget stays authoritative;
// this ledger only bridges the gap Go embedding cannot cross.
type PluginWidgetManifest struct {
	PluginID string
	Dir      string
	JSON     string
}

var pluginWidgetManifests = []PluginWidgetManifest{}

// PluginWidgetManifests returns every plugin-owned Widget manifest in
// directory order.
func PluginWidgetManifests() []PluginWidgetManifest {
	out := make([]PluginWidgetManifest, len(pluginWidgetManifests))
	copy(out, pluginWidgetManifests)
	return out
}
