// Code generated by scripts/generate-browser-capabilities.mjs; DO NOT EDIT.
// Source: apps/player-web/capabilities.json

export type BrowserCapabilityStatus =
  "supported" | "conditional" | "unsupported" | "not_applicable";

// Studio shows localized text from its own locale files, so the English
// labels and notes stay in the matrix, the Go table and the documentation.
export interface BrowserCapability {
  readonly id: string;
  readonly status: BrowserCapabilityStatus;
}

export interface BrowserCommand {
  readonly type: string;
}

export const BROWSER_CAPABILITIES: readonly BrowserCapability[] = [
  { id: "playback.shared_runtime", status: "supported" },
  { id: "playback.playlists", status: "supported" },
  { id: "playback.layouts", status: "supported" },
  { id: "playback.widgets", status: "supported" },
  { id: "scheduling.server_selected", status: "supported" },
  { id: "scheduling.takeovers", status: "supported" },
  { id: "power.active_hours", status: "supported" },
  { id: "offline.last_verified_activation", status: "supported" },
  { id: "offline.future_schedule_evaluation", status: "unsupported" },
  { id: "offline.persistent_media_cache", status: "conditional" },
  { id: "activity.proof_of_play", status: "supported" },
  { id: "commands.operator", status: "supported" },
  { id: "install.pwa", status: "supported" },
  { id: "playback.synchronized", status: "unsupported" },
  { id: "capture.watch_live", status: "unsupported" },
  { id: "website.privileged", status: "unsupported" },
  { id: "display.cec_ddc", status: "unsupported" },
  { id: "device.reboot", status: "unsupported" },
  { id: "updates.native", status: "not_applicable" },
  { id: "network.os_configuration", status: "unsupported" },
];

export const BROWSER_COMMANDS: readonly BrowserCommand[] = [
  { type: "sync_now" },
  { type: "reload_playback" },
  { type: "identify_screen" },
  { type: "retry_current_item" },
  { type: "skip_current_item" },
];

const COMMAND_TYPES: ReadonlySet<string> = new Set(
  BROWSER_COMMANDS.map((command) => command.type),
);

/** True when a Browser Player can truthfully perform this command type. */
export function browserSupportsCommand(type: string): boolean {
  return COMMAND_TYPES.has(type);
}

export function browserCapabilityStatus(
  id: string,
): BrowserCapabilityStatus | undefined {
  return BROWSER_CAPABILITIES.find((entry) => entry.id === id)?.status;
}
