// Generated by apps/ios/scripts/generate-navigation-icons.mjs from Lucide
// 1.48.0. Do not edit; run `npm run ios:icons:generate`.

extension NavigationIcon {
    /// The Lucide icon Studio shows for each token, as an asset name in the
    /// app's catalog. From apps/dashboard/src/navigation/NavigationIcon.tsx
    /// and apps/dashboard/src/components/studio/actionIcons.tsx.
    static let images: [String: String] = [
        "home": "Lucide/house",
        "screens": "Lucide/monitor",
        "groups": "Lucide/users",
        "media": "Lucide/image",
        "widgets": "Lucide/blocks",
        "data": "Lucide/database",
        "playlists": "Lucide/list-video",
        "layouts": "Lucide/panels-top-left",
        "campaigns": "Lucide/megaphone",
        "schedules": "Lucide/calendar-clock",
        "plugins": "Lucide/puzzle",
        "activity": "Lucide/activity",
        "settings": "Lucide/settings",
        "plugin": "Lucide/puzzle",
        "open": "Lucide/arrow-up-right",
        "edit": "Lucide/square-pen",
        "rename": "Lucide/pencil",
        "copy": "Lucide/copy",
        "duplicate": "Lucide/copy",
        "trash": "Lucide/trash",
        "delete": "Lucide/trash",
        "archive": "Lucide/archive",
        "restore": "Lucide/archive-restore",
        "refresh": "Lucide/refresh-cw",
        "restart": "Lucide/refresh-cw",
        "play": "Lucide/play",
        "select": "Lucide/list-checks",
        "group": "Lucide/users",
        "remove": "Lucide/package-minus",
        "details": "Lucide/pencil",
        "airplay": "Lucide/airplay",
    ]

    /// Studio's generic navigation icon.
    public static let generic = "Lucide/circle-dashed"
}
