// Generated by apps/ios/scripts/generate-navigation-icons.mjs from Lucide
// 1.48.0. Do not edit; run `npm run ios:icons:generate`.

extension NavigationIcon {
    /// The Lucide icon Studio shows for each token, as an asset name in the
    /// app's catalog. From apps/dashboard/src/navigation/NavigationIcon.tsx.
    static let images: [String: String] = [
        "home": "Lucide/house",
        "screens": "Lucide/monitor",
        "groups": "Lucide/users",
        "media": "Lucide/image",
        "widgets": "Lucide/blocks",
        "data": "Lucide/database",
        "playlists": "Lucide/list-video",
        "layouts": "Lucide/panels-top-left",
        "campaigns": "Lucide/megaphone",
        "schedules": "Lucide/calendar-clock",
        "plugins": "Lucide/puzzle",
        "activity": "Lucide/activity",
        "settings": "Lucide/settings",
        "plugin": "Lucide/puzzle",
    ]

    /// Studio's generic navigation icon.
    public static let generic = "Lucide/circle-dashed"
}
