// Code generated by scripts/generate-browser-capabilities.mjs; DO NOT EDIT.
// Source: apps/player-web/capabilities.json

package devices

// BrowserCapability is one row of the Browser Player capability matrix.
type BrowserCapability struct {
	ID     string
	Label  string
	Status string
	Note   string
}

var browserCapabilities = []BrowserCapability{
	{ID: "playback.shared_runtime", Label: "Image and video playback", Status: "supported", Note: "The shared Player Runtime plays them."},
	{ID: "playback.playlists", Label: "Playlists and transitions", Status: "supported", Note: "The shared Player Runtime advances items and runs transitions."},
	{ID: "playback.layouts", Label: "Layouts", Status: "supported", Note: "Layout zones render in the shared Player Runtime."},
	{ID: "playback.widgets", Label: "Widgets", Status: "supported", Note: "Widgets and Widget components render in the shared Player Runtime."},
	{ID: "scheduling.server_selected", Label: "Content schedules chosen by the server", Status: "supported", Note: "The server selects the content. The Browser Player does not rank schedules."},
	{ID: "scheduling.takeovers", Label: "Takeovers", Status: "supported", Note: "The server selects a Takeover like any other content."},
	{ID: "power.active_hours", Label: "Active hours and rest", Status: "supported", Note: "The shared active-hours policy runs in the browser, including while the server is unreachable. The browser shows the rest surface. It does not power off the display."},
	{ID: "offline.last_verified_activation", Label: "Last verified content offline", Status: "supported", Note: "The last completely prepared activation continues while the server is unreachable."},
	{ID: "offline.future_schedule_evaluation", Label: "Choosing future content schedules offline", Status: "unsupported", Note: "The server chooses content. The Browser Player waits for the server to choose again."},
	{ID: "offline.persistent_media_cache", Label: "Persistent media cache", Status: "conditional", Note: "Supported when the browser grants persistent storage. Otherwise the browser can remove downloaded content."},
	{ID: "activity.proof_of_play", Label: "Activity and proof of play", Status: "supported", Note: "The Browser Player reports the same Activity events as other Players. It keeps them in a durable local queue until the server accepts them."},
	{ID: "commands.operator", Label: "Identify, retry, skip, sync and reload", Status: "supported", Note: "The Browser Player runs the commands listed under Commands."},
	{ID: "install.pwa", Label: "Installed app", Status: "supported", Note: "Chrome and Microsoft Edge can install each Browser Player as its own app."},
	{ID: "playback.synchronized", Label: "Synchronized playback", Status: "unsupported", Note: "The Browser Player does not produce shared timeline anchors."},
	{ID: "capture.watch_live", Label: "Watch Live and screenshots", Status: "unsupported", Note: "A browser cannot capture its own display without a user prompt."},
	{ID: "website.privileged", Label: "Websites and YouTube", Status: "unsupported", Note: "Browser Player v1 has no isolated Website surface. The browser frame boundary is not weakened."},
	{ID: "display.cec_ddc", Label: "Display control (CEC and DDC)", Status: "unsupported", Note: "A web page cannot control the display."},
	{ID: "device.reboot", Label: "Device restart", Status: "unsupported", Note: "A web page cannot restart the device."},
	{ID: "updates.native", Label: "Player updates", Status: "not_applicable", Note: "The server supplies the Browser Player. Update targeting excludes it."},
	{ID: "network.os_configuration", Label: "Operating system network setup", Status: "unsupported", Note: "A web page cannot change the network."},
}

var browserCommands = map[string]bool{
	"sync_now":           true,
	"reload_playback":    true,
	"identify_screen":    true,
	"retry_current_item": true,
	"skip_current_item":  true,
}

// BrowserCapabilities returns a copy of the Browser Player capability matrix.
func BrowserCapabilities() []BrowserCapability {
	return append([]BrowserCapability(nil), browserCapabilities...)
}

// BrowserSupportsCommand reports whether a Browser Player can perform the
// command type. Every other command type is refused for a Browser Screen.
func BrowserSupportsCommand(commandType string) bool { return browserCommands[commandType] }

// BrowserSupportedCommands returns the supported command types in matrix order.
func BrowserSupportedCommands() []string {
	return []string{
		"sync_now",
		"reload_playback",
		"identify_screen",
		"retry_current_item",
		"skip_current_item",
	}
}
