// Code generated by widgetctl from widgets/*/tilecast.widget.json. DO NOT EDIT.
// Run `npm run widgets:generate`.
package org.tilecast.player.runtime

/**
 * First-class Widget components bundled in the Player Runtime, as Players
 * report them in nativePresentationCapabilities (docs/widgets-v2.md §7).
 * Generated from the same Widget manifests as the runtime and Edge
 * capability lists; a new Widget needs no handwritten Android change.
 */
object WidgetComponentCapabilities {
    const val COMPONENT_PRESENTATION_SCHEMA_VERSION = 2
    val WIDGET_COMPONENT_CAPABILITIES: Map<String, Int> = mapOf(
        "widget.tilecast.agenda" to 1,
        "widget.tilecast.cards" to 1,
        "widget.tilecast.chart" to 1,
        "widget.tilecast.clock" to 2,
        "widget.tilecast.countdown" to 1,
        "widget.tilecast.image-notice" to 1,
        "widget.tilecast.list" to 1,
        "widget.tilecast.menu-board" to 1,
        "widget.tilecast.metrics" to 1,
        "widget.tilecast.news" to 1,
        "widget.tilecast.progress" to 1,
        "widget.tilecast.qr-code" to 1,
        "widget.tilecast.spotlight" to 1,
        "widget.tilecast.status" to 1,
        "widget.tilecast.table" to 1,
        "widget.tilecast.text" to 1,
        "widget.tilecast.ticker" to 1,
        "widget.tilecast.timeline" to 1,
        "widget.tilecast.weather" to 1,
    )
}
