package edge

import (
	"bytes"
	"crypto/ed25519"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

// These tests hold the Go implementation to the same golden files as the
// Rust daemon (packages/edge-protocol/fixtures). The signed fixture is
// generated by Rust; Go must reproduce every byte independently.

func fixturePath(parts ...string) string {
	return filepath.Join(append([]string{"..", "..", "..", "..", "packages", "edge-protocol", "fixtures"}, parts...)...)
}

func readFixture(t *testing.T, parts ...string) map[string]json.RawMessage {
	t.Helper()
	data, err := os.ReadFile(fixturePath(parts...))
	if err != nil {
		t.Fatal(err)
	}
	var out map[string]json.RawMessage
	if err := json.Unmarshal(data, &out); err != nil {
		t.Fatal(err)
	}
	return out
}

func TestCanonicalJSONFixtures(t *testing.T) {
	fixture := readFixture(t, "canonical-json", "cases.json")
	var valid []struct{ Name, Input, Canonical string }
	var invalid, notCanonical []struct{ Name, Input string }
	if err := json.Unmarshal(fixture["valid"], &valid); err != nil {
		t.Fatal(err)
	}
	if err := json.Unmarshal(fixture["invalid"], &invalid); err != nil {
		t.Fatal(err)
	}
	if err := json.Unmarshal(fixture["notCanonical"], &notCanonical); err != nil {
		t.Fatal(err)
	}
	for _, c := range valid {
		out, err := CanonicalizeJSON([]byte(c.Input))
		if err != nil {
			t.Fatalf("%s: %v", c.Name, err)
		}
		if string(out) != c.Canonical {
			t.Fatalf("%s: got %q want %q", c.Name, out, c.Canonical)
		}
		if _, err := ParseCanonical(out); err != nil {
			t.Fatalf("%s reparse: %v", c.Name, err)
		}
	}
	for _, c := range invalid {
		if _, err := CanonicalizeJSON([]byte(c.Input)); err == nil {
			t.Fatalf("%s must not canonicalize", c.Name)
		}
	}
	for _, c := range notCanonical {
		if _, err := ParseCanonical([]byte(c.Input)); err == nil {
			t.Fatalf("%s must be rejected", c.Name)
		}
	}
}

func TestSignedChangeFixturesMatchRustBytes(t *testing.T) {
	fixture := readFixture(t, "signed", "server-change-v1.json")
	var seedHex, keyID string
	_ = json.Unmarshal(fixture["testSeedHex"], &seedHex)
	_ = json.Unmarshal(fixture["keyId"], &keyID)
	seed, err := hex.DecodeString(seedHex)
	if err != nil {
		t.Fatal(err)
	}
	key := ed25519.NewKeyFromSeed(seed)
	public := key.Public().(ed25519.PublicKey)
	if KeyID(public) != keyID {
		t.Fatalf("key id %s != fixture %s", KeyID(public), keyID)
	}
	var cases []struct {
		Name                  string          `json:"name"`
		Purpose               string          `json:"purpose"`
		Body                  json.RawMessage `json:"body"`
		CanonicalBody         string          `json:"canonicalBody"`
		SigningInputBase64url string          `json:"signingInputBase64url"`
		Document              SignedDocument  `json:"document"`
	}
	if err := json.Unmarshal(fixture["cases"], &cases); err != nil {
		t.Fatal(err)
	}
	for _, c := range cases {
		decoder := json.NewDecoder(bytes.NewReader(c.Body))
		decoder.UseNumber()
		var body map[string]any
		if err := decoder.Decode(&body); err != nil {
			t.Fatal(err)
		}
		document, canonical, err := Sign(key, c.Purpose, body)
		if err != nil {
			t.Fatalf("%s: %v", c.Name, err)
		}
		if string(canonical) != c.CanonicalBody {
			t.Fatalf("%s: canonical body differs\n got %s\nwant %s", c.Name, canonical, c.CanonicalBody)
		}
		if base64.RawURLEncoding.EncodeToString(signingInput(c.Purpose, canonical)) != c.SigningInputBase64url {
			t.Fatalf("%s: signing input differs", c.Name)
		}
		if document != c.Document {
			t.Fatalf("%s: document differs\n got %+v\nwant %+v", c.Name, document, c.Document)
		}
		if _, err := Verify(c.Document, c.Purpose, public); err != nil {
			t.Fatalf("%s: verify: %v", c.Name, err)
		}
	}
	var tampered []struct {
		Name     string         `json:"name"`
		Document SignedDocument `json:"document"`
	}
	if err := json.Unmarshal(fixture["tampered"], &tampered); err != nil {
		t.Fatal(err)
	}
	for _, c := range tampered {
		if _, err := Verify(c.Document, PurposeServerChange, public); err == nil {
			t.Fatalf("%s must not verify", c.Name)
		}
	}
}
