/**
 * Generated artifacts. Only what a toolchain cannot discover by itself is
 * generated: the portable JSON Schema, the capability lists hosts that
 * are not built with Vite advertise (the Electron main process and the Edge
 * daemon), and the plugin-owned Widget ledger the Server embeds. The Player
 * Runtime and Studio discover Widgets with import.meta.glob; the Server
 * embeds root manifests with go:embed and reads plugin-owned manifests
 * from the generated ledger, because Go embedding cannot reach outside
 * the widgets package tree into plugins/.
 */
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import * as prettier from "prettier";
import { MANIFEST_FILE } from "./repo.ts";
import { widgetManifestJSONSchema } from "../../src/manifest.ts";
import {
  buildSandboxFrameDocument,
  SANDBOX_BUNDLE_PLACEHOLDER,
} from "../../src/sandboxed-executor.ts";
import type { Repo } from "./repo.ts";

export const JSON_SCHEMA =
  "packages/widget-sdk/schema/tilecast-widget.schema.json";
export const RUNTIME_CAPABILITIES =
  "packages/player-runtime/src/widgets/capabilities.gen.ts";
export const EDGE_CAPABILITIES =
  "apps/edge/tilecastd/src/widget_capabilities.rs";
export const WINDOWS_CAPABILITIES =
  "apps/player-windows/src/widget_capabilities.rs";
export const ANDROID_CAPABILITIES =
  "apps/player-android/app/src/main/java/org/tilecast/player/runtime/WidgetComponentCapabilities.gen.kt";
export const ANDROID_NATIVE_CAPABILITIES =
  "apps/player-android/native/src/widget_capabilities.rs";
/** Server-side ledger of plugin-owned Widget manifests (package widgets). */
export const PLUGIN_WIDGET_LEDGER = "widgets/plugin_widgets.gen.go";
/**
 * Server-side sandboxed Widget frame template. The Server interpolates
 * one escaped verified bundle into the placeholder; the template bytes
 * stay identical to what the spike harness measures.
 */
export const SANDBOX_FRAME_TEMPLATE =
  "apps/server/internal/extensions/sandbox/frame.gen.go";

/** `widget.<type>` → version for every Widget, sorted by capability. */
export function capabilities(repo: Repo): [string, number][] {
  return repo.widgets
    .map(
      (widget) =>
        [
          `widget.${widget.manifest.component.type}`,
          widget.manifest.component.version,
        ] as [string, number],
    )
    .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
}

function runtimeCapabilities(repo: Repo): string {
  const entries = capabilities(repo)
    .map(([name, version]) => `  ${JSON.stringify(name)}: ${version},`)
    .join("\n");
  return `// Code generated by widgetctl from widgets/*/tilecast.widget.json. DO NOT EDIT.
// Run \`npm run widgets:generate\`.

/**
 * The first-class Widget components this runtime bundles, as Players report
 * them in nativePresentationCapabilities (docs/widgets-v2.md §7). Hosts that
 * are not built with Vite (the Electron main process) import this list; the
 * runtime's tests prove it equals what discovery finds.
 */
export const WIDGET_COMPONENT_CAPABILITIES: Readonly<Record<string, number>> =
  Object.freeze({
${entries}
  });

/** Latest component presentation schema supported by this runtime. */
export const COMPONENT_PRESENTATION_SCHEMA_VERSION = 3;
`;
}

function rustComponentsList(repo: Repo): string {
  // The layout rustfmt (max_width 120) keeps, so `cargo fmt` never makes
  // the generated file stale: one line when it fits, one entry per line
  // otherwise.
  const tuples = capabilities(repo).map(
    ([name, version]) => `(${JSON.stringify(name)}, ${version})`,
  );
  const head = "pub const WIDGET_COMPONENTS: &[(&str, u32)] = &[";
  const oneLine = `${head}${tuples.join(", ")}];`;
  return oneLine.length <= 120
    ? oneLine
    : `${head}\n${tuples.map((tuple) => `    ${tuple},`).join("\n")}\n];`;
}

function edgeCapabilities(repo: Repo): string {
  const list = rustComponentsList(repo);
  return `// Code generated by widgetctl from widgets/*/tilecast.widget.json. DO NOT EDIT.
// Run \`npm run widgets:generate\`.

//! First-class Widget components bundled in the Player Runtime this daemon
//! ships with (docs/widgets-v2.md §7). The renderer runs the same runtime
//! artifact, so the list is fixed at release build time.

/// Latest component presentation schema supported by this runtime.
pub const COMPONENT_PRESENTATION_SCHEMA: u32 = 3;

/// \`widget.<type>\` capability and component version.
${list}
`;
}

function windowsCapabilities(repo: Repo): string {
  const list = rustComponentsList(repo);
  return `// Code generated by widgetctl from widgets/*/tilecast.widget.json. DO NOT EDIT.
// Run \`npm run widgets:generate\`.

//! First-class Widget components bundled in the Player Runtime this player
//! ships with (docs/widgets-v2.md §7). The renderer runs the same runtime
//! artifact, so the list is fixed at release build time.

/// Latest component presentation schema supported by this runtime.
pub const COMPONENT_PRESENTATION_SCHEMA: u32 = 3;

/// \`widget.<type>\` capability and component version.
${list}
`;
}

function androidNativeCapabilities(repo: Repo): string {
  // Same rustfmt-stable layout as the Edge output.
  const tuples = capabilities(repo).map(
    ([name, version]) => `(${JSON.stringify(name)}, ${version})`,
  );
  const head = "pub const WIDGET_COMPONENTS: &[(&str, u32)] = &[";
  const oneLine = `${head}${tuples.join(", ")}];`;
  const list =
    oneLine.length <= 120
      ? oneLine
      : `${head}\n${tuples.map((tuple) => `    ${tuple},`).join("\n")}\n];`;
  return `// Code generated by widgetctl from widgets/*/tilecast.widget.json. DO NOT EDIT.
// Run \`npm run widgets:generate\`.

//! First-class Widget components bundled in the Player Runtime the Android
//! Player ships with (docs/widgets-v2.md §7). The renderer runs the same
//! runtime artifact, so the list is fixed at release build time.

/// Latest component presentation schema the Android host applies: 2.
/// Schema 3 (declared empty policy) needs host-side empty-skip handling
/// the Android Player has not implemented yet; manifests using it are
/// incompatible until it does.
pub const COMPONENT_PRESENTATION_SCHEMA: u32 = 2;

/// \`widget.<type>\` capability and component version.
${list}
`;
}

export function androidCapabilities(repo: Repo): string {
  const entries = capabilities(repo)
    .map(([name, version]) => `        ${JSON.stringify(name)} to ${version},`)
    .join("\n");
  return `// Code generated by widgetctl from widgets/*/tilecast.widget.json. DO NOT EDIT.
// Run \`npm run widgets:generate\`.
package org.tilecast.player.runtime

/**
 * First-class Widget components bundled in the Player Runtime, as Players
 * report them in nativePresentationCapabilities (docs/widgets-v2.md §7).
 * Generated from the same Widget manifests as the runtime and Edge
 * capability lists; a new Widget needs no handwritten Android change.
 */
object WidgetComponentCapabilities {
    const val COMPONENT_PRESENTATION_SCHEMA_VERSION = 2
    val WIDGET_COMPONENT_CAPABILITIES: Map<String, Int> = mapOf(
${entries}
    )
}
`;
}

async function format(text: string, path: string, root: string) {
  const options = (await prettier.resolveConfig(join(root, path))) ?? {};
  return prettier.format(text, { ...options, filepath: join(root, path) });
}

/** Quote a string as a Go interpreted string literal, preserving exact bytes. */
export function goQuoted(value: string): string {
  let out = '"';
  for (const char of value) {
    const code = char.codePointAt(0) ?? 0;
    switch (char) {
      case "\\":
        out += "\\\\";
        break;
      case '"':
        out += '\\"';
        break;
      case "\n":
        out += "\\n";
        break;
      case "\r":
        out += "\\r";
        break;
      case "\t":
        out += "\\t";
        break;
      default:
        if (code < 0x20 || code === 0x7f) {
          out += `\\u00${code.toString(16).padStart(2, "0")}`;
        } else {
          out += char;
        }
    }
  }
  return `${out}"`;
}

/**
 * The plugin-owned Widget ledger: every plugins Widget manifest with its
 * stable plugin identity and exact manifest bytes, in directory order. The
 * file is gofmt-clean by construction (tabs, aligned struct fields,
 * single-line entries); widgets:check fails when the committed file
 * differs from a fresh generation.
 */
export function pluginWidgetLedger(
  widgets: { dir: string; pluginId: string; json: string }[],
): string {
  const entries = [...widgets]
    .sort((a, b) => (a.dir < b.dir ? -1 : a.dir > b.dir ? 1 : 0))
    .map(
      (widget) =>
        `\t{PluginID: ${goQuoted(widget.pluginId)}, Dir: ${goQuoted(widget.dir)}, JSON: ${goQuoted(widget.json)}}`,
    )
    .join(",\n");
  const table =
    entries.length === 0
      ? "var pluginWidgetManifests = []PluginWidgetManifest{}"
      : `var pluginWidgetManifests = []PluginWidgetManifest{\n${entries},\n}`;
  return `// Code generated by widgetctl from plugin-owned tilecast.widget.json files. DO NOT EDIT.
// Run \`npm run widgets:generate\`.

package widgets

// PluginWidgetManifest is one plugin-owned Widget manifest composed into
// the Server's content catalog. PluginID is the stable id from the owning
// plugin's tilecast.plugin.json (never the plugin directory basename),
// Dir is the Widget's directory relative to the repository root, and JSON
// carries the exact tilecast.widget.json bytes for validation and
// fingerprinting. The manifest beside the Widget stays authoritative;
// this ledger only bridges the gap Go embedding cannot cross.
type PluginWidgetManifest struct {
\tPluginID string
\tDir      string
\tJSON     string
}

${table}

// PluginWidgetManifests returns every plugin-owned Widget manifest in
// directory order.
func PluginWidgetManifests() []PluginWidgetManifest {
\tout := make([]PluginWidgetManifest, len(pluginWidgetManifests))
\tcopy(out, pluginWidgetManifests)
\treturn out
}
`;
}

/**
 * The sandboxed Widget frame template as a Go source file. The document
 * is byte-identical to `buildSandboxFrameDocument` over the placeholder;
 * the Server replaces the placeholder's single occurrence with the
 * escaped verified bundle. gofmt-clean by construction.
 */
export function sandboxFrameTemplate(): string {
  const template = buildSandboxFrameDocument(SANDBOX_BUNDLE_PLACEHOLDER);
  const occurrences = template.split(SANDBOX_BUNDLE_PLACEHOLDER).length - 1;
  if (occurrences !== 1) {
    throw new Error(
      `sandbox frame template must hold exactly one bundle slot, found ${occurrences}`,
    );
  }
  return `// Code generated by widgetctl from the sandbox frame builder. DO NOT EDIT.
// Run \`npm run widgets:generate\`.

package sandbox

// BundlePlaceholder marks the single slot in Template that Assemble
// replaces with the escaped verified bundle.
const BundlePlaceholder = ${goQuoted(SANDBOX_BUNDLE_PLACEHOLDER)}

// Template is the sandboxed Widget frame document: the bootstrap first,
// then the bundle slot. It is byte-identical to what the spike harness
// in packages/widget-sdk/spike measures.
const Template = ${goQuoted(template)}
`;
}

export async function generate(repo: Repo): Promise<Map<string, string>> {
  const files = new Map<string, string>();
  files.set(SANDBOX_FRAME_TEMPLATE, sandboxFrameTemplate());
  files.set(
    JSON_SCHEMA,
    await format(
      JSON.stringify(widgetManifestJSONSchema()),
      JSON_SCHEMA,
      repo.root,
    ),
  );
  files.set(
    RUNTIME_CAPABILITIES,
    await format(runtimeCapabilities(repo), RUNTIME_CAPABILITIES, repo.root),
  );
  files.set(EDGE_CAPABILITIES, edgeCapabilities(repo));
  files.set(WINDOWS_CAPABILITIES, windowsCapabilities(repo));
  files.set(ANDROID_CAPABILITIES, androidCapabilities(repo));
  files.set(ANDROID_NATIVE_CAPABILITIES, androidNativeCapabilities(repo));
  const pluginWidgets: { dir: string; pluginId: string; json: string }[] = [];
  for (const widget of repo.widgets) {
    if (widget.source.kind !== "plugin") continue;
    pluginWidgets.push({
      dir: widget.dir,
      pluginId: widget.source.pluginId,
      json: readFileSync(join(widget.path, MANIFEST_FILE), "utf8"),
    });
  }
  files.set(PLUGIN_WIDGET_LEDGER, pluginWidgetLedger(pluginWidgets));
  return files;
}

/** Generated files whose committed content differs from a fresh generation. */
export function stale(repo: Repo, files: Map<string, string>): string[] {
  return [...files]
    .filter(([path, content]) => {
      const full = join(repo.root, path);
      return !existsSync(full) || readFileSync(full, "utf8") !== content;
    })
    .map(([path]) => path);
}
