/**
 * Generated artifacts. Only what a toolchain cannot discover by itself is
 * generated: the portable JSON Schema, and the capability lists hosts that
 * are not built with Vite advertise (the Electron main process and the Edge
 * daemon). The Player Runtime and Studio discover Widgets with
 * import.meta.glob; the Server embeds the manifests with go:embed.
 */
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import * as prettier from "prettier";
import { widgetManifestJSONSchema } from "../../src/manifest.ts";
import type { Repo } from "./repo.ts";

export const JSON_SCHEMA =
  "packages/widget-sdk/schema/tilecast-widget.schema.json";
export const RUNTIME_CAPABILITIES =
  "packages/player-runtime/src/widgets/capabilities.gen.ts";
export const EDGE_CAPABILITIES =
  "apps/edge/tilecastd/src/widget_capabilities.rs";

/** `widget.<type>` → version for every Widget, sorted by capability. */
export function capabilities(repo: Repo): [string, number][] {
  return repo.widgets
    .map(
      (widget) =>
        [
          `widget.${widget.manifest.component.type}`,
          widget.manifest.component.version,
        ] as [string, number],
    )
    .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
}

function runtimeCapabilities(repo: Repo): string {
  const entries = capabilities(repo)
    .map(([name, version]) => `  ${JSON.stringify(name)}: ${version},`)
    .join("\n");
  return `// Code generated by widgetctl from widgets/*/tilecast.widget.json. DO NOT EDIT.
// Run \`npm run widgets:generate\`.

/**
 * The first-class Widget components this runtime bundles, as Players report
 * them in nativePresentationCapabilities (docs/widgets-v2.md §7). Hosts that
 * are not built with Vite (the Electron main process) import this list; the
 * runtime's tests prove it equals what discovery finds.
 */
export const WIDGET_COMPONENT_CAPABILITIES: Readonly<Record<string, number>> =
  Object.freeze({
${entries}
  });

/** Presentation schema of kind "component" presentations. */
export const COMPONENT_PRESENTATION_SCHEMA_VERSION = 2;
`;
}

function edgeCapabilities(repo: Repo): string {
  // The layout rustfmt (max_width 120) keeps, so `cargo fmt` never makes
  // the generated file stale: one line when it fits, one entry per line
  // otherwise.
  const tuples = capabilities(repo).map(
    ([name, version]) => `(${JSON.stringify(name)}, ${version})`,
  );
  const head = "pub const WIDGET_COMPONENTS: &[(&str, u32)] = &[";
  const oneLine = `${head}${tuples.join(", ")}];`;
  const list =
    oneLine.length <= 120
      ? oneLine
      : `${head}\n${tuples.map((tuple) => `    ${tuple},`).join("\n")}\n];`;
  return `// Code generated by widgetctl from widgets/*/tilecast.widget.json. DO NOT EDIT.
// Run \`npm run widgets:generate\`.

//! First-class Widget components bundled in the Player Runtime this daemon
//! ships with (docs/widgets-v2.md §7). The renderer runs the same runtime
//! artifact, so the list is fixed at release build time.

/// Presentation schema of kind "component" presentations.
pub const COMPONENT_PRESENTATION_SCHEMA: u32 = 2;

/// \`widget.<type>\` capability and component version.
${list}
`;
}

async function format(text: string, path: string, root: string) {
  const options = (await prettier.resolveConfig(join(root, path))) ?? {};
  return prettier.format(text, { ...options, filepath: join(root, path) });
}

export async function generate(repo: Repo): Promise<Map<string, string>> {
  const files = new Map<string, string>();
  files.set(
    JSON_SCHEMA,
    await format(
      JSON.stringify(widgetManifestJSONSchema()),
      JSON_SCHEMA,
      repo.root,
    ),
  );
  files.set(
    RUNTIME_CAPABILITIES,
    await format(runtimeCapabilities(repo), RUNTIME_CAPABILITIES, repo.root),
  );
  files.set(EDGE_CAPABILITIES, edgeCapabilities(repo));
  return files;
}

/** Generated files whose committed content differs from a fresh generation. */
export function stale(repo: Repo, files: Map<string, string>): string[] {
  return [...files]
    .filter(([path, content]) => {
      const full = join(repo.root, path);
      return !existsSync(full) || readFileSync(full, "utf8") !== content;
    })
    .map(([path]) => path);
}
