package database

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"os"
	"strings"
	"testing"

	"github.com/tilecast/tilecast/packages/plugin-sdk/go/plugin"
)

func TestEmbeddedMigrationsAreCollectible(t *testing.T) {
	if _, err := LatestMigrationVersion(); err != nil {
		t.Fatalf("collect embedded migrations: %v", err)
	}
}

// migrations.lock.json is generated by pluginctl from the files on disk. The
// binary's catalog must match it exactly: same versions, same owners, same
// bytes. That catches a plugin whose migrations are not embedded, a shipped
// migration whose content changed while it moved into a plugin directory,
// and two owners reserving the same version.
func TestCatalogMatchesMigrationLock(t *testing.T) {
	data, err := os.ReadFile("migrations.lock.json")
	if err != nil {
		t.Fatal(err)
	}
	var lock []struct {
		Version int64  `json:"version"`
		File    string `json:"file"`
		Owner   string `json:"owner"`
		SHA256  string `json:"sha256"`
	}
	if err = json.Unmarshal(data, &lock); err != nil {
		t.Fatal(err)
	}
	catalog, err := Catalog()
	if err != nil {
		t.Fatal(err)
	}
	if len(catalog) != len(lock) {
		t.Fatalf("catalog has %d migrations, lock has %d; run npm run plugins:generate", len(catalog), len(lock))
	}
	for index, entry := range catalog {
		sum := sha256.Sum256(entry.Content)
		want := lock[index]
		if entry.Version != want.Version || entry.File != want.File || entry.Owner != want.Owner || hex.EncodeToString(sum[:]) != want.SHA256 {
			t.Fatalf("catalog entry %d (%s, %s) does not match the lock (%s, %s)", index, entry.File, entry.Owner, want.File, want.Owner)
		}
	}
	latest, err := LatestMigrationVersion()
	if err != nil || latest != lock[len(lock)-1].Version {
		t.Fatalf("LatestMigrationVersion() = %d, %v", latest, err)
	}
}

const pluginManifest = `{"apiVersion":1,"id":"%s","definitionVersion":1,"name":"Test","description":"Test plugin.",
"category":"Workflow","icon":"puzzle","maintainers":["@gbyo"],"instanceNoun":{"singular":"item","plural":"items"},
"migrations":"./migrations"}`

type migratingPlugin struct{ plugin.Bundle }

func testPlugin(t *testing.T, id string, files map[string]string) plugin.Plugin {
	t.Helper()
	fsys := memoryFS{}
	for name, content := range files {
		fsys[name] = []byte(content)
	}
	return &migratingPlugin{plugin.NewBundle([]byte(strings.Replace(pluginManifest, "%s", id, 1)), fsys)}
}

func TestPluginMigrationsJoinTheGlobalSequence(t *testing.T) {
	const body = "-- +goose Up\nSELECT 1;\n-- +goose Down\nSELECT 1;\n"
	entries, err := catalogFrom([]plugin.Plugin{testPlugin(t, "late_plugin", map[string]string{"99999_late_plugin.sql": body})})
	if err != nil {
		t.Fatal(err)
	}
	last := entries[len(entries)-1]
	if last.Version != 99999 || last.Owner != "late_plugin" {
		t.Fatalf("plugin migration not in sequence: %+v", last)
	}

	// A plugin may not reuse a version core (or another plugin) already has.
	if _, err = catalogFrom([]plugin.Plugin{testPlugin(t, "clash_plugin", map[string]string{"00001_clash.sql": body})}); err == nil ||
		!strings.Contains(err.Error(), "00001_foundation.sql (core)") {
		t.Fatalf("duplicate version accepted: %v", err)
	}
}
