// Code generated by scripts/generate-player-contracts.mjs; DO NOT EDIT.
// Source: packages/manifest-schema/presentation-capabilities.json

package presentationcaps

var sharedRuntime = map[string]int{
	"binding.core":                2,
	"collection.conditional":      2,
	"collection.grouped_sections": 1,
	"collection.repeat":           2,
	"content.asset_image":         2,
	"content.badge":               1,
	"content.bar_chart":           2,
	"content.donut_chart":         2,
	"content.icon":                2,
	"content.line_chart":          2,
	"content.marquee":             1,
	"content.progress":            2,
	"content.qr_code":             1,
	"content.text":                1,
	"environment.time":            1,
	"format.typed":                2,
	"layout.box":                  1,
	"layout.column":               1,
	"layout.divider":              1,
	"layout.grid":                 1,
	"layout.row":                  1,
	"layout.spacer":               1,
	"layout.stack":                1,
	"layout.surface":              1,
	"playback.auto_skip":          1,
	"selection.relative_date":     1,
	"selection.temporal":          1,
}

var baseline = map[string]int{
	"binding.core":                2,
	"collection.conditional":      2,
	"collection.grouped_sections": 1,
	"collection.repeat":           2,
	"content.asset_image":         2,
	"content.badge":               1,
	"content.bar_chart":           2,
	"content.donut_chart":         2,
	"content.icon":                2,
	"content.line_chart":          2,
	"content.marquee":             1,
	"content.progress":            2,
	"content.qr_code":             1,
	"content.text":                1,
	"format.typed":                2,
	"layout.box":                  1,
	"layout.column":               1,
	"layout.divider":              1,
	"layout.grid":                 1,
	"layout.row":                  1,
	"layout.spacer":               1,
	"layout.stack":                1,
	"layout.surface":              1,
	"playback.auto_skip":          1,
	"selection.relative_date":     1,
	"selection.temporal":          1,
}

// Supports reports whether name belongs to the declarative presentation vocabulary.
func Supports(name string) bool {
	_, ok := sharedRuntime[name]
	return ok
}

// Version returns the maximum version implemented by the shared Player Runtime.
func Version(name string) int { return sharedRuntime[name] }

// SharedRuntime returns a copy of the shared-runtime capability profile.
func SharedRuntime() map[string]int { return clone(sharedRuntime) }

// Baseline returns a copy of the compatibility floor used for legacy Players.
func Baseline() map[string]int { return clone(baseline) }

func clone(source map[string]int) map[string]int {
	result := make(map[string]int, len(source))
	for name, version := range source {
		result[name] = version
	}
	return result
}
